# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x05proto\"?\n\x10\x46\x65tchDataRequest\x12\x0f\n\x07symbols\x18\x02 \x03(\t\x12\r\n\x05start\x18\x03 \x01(\t\x12\x0b\n\x03\x65nd\x18\x04 \x01(\t\" \n\x10\x46\x65tchDataReponse\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"O\n\x0fLoadDataRequest\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\t\x12\x0b\n\x03\x65nd\x18\x04 \x01(\t\x12\x10\n\x08\x62\x61r_type\x18\x05 \x01(\t\"/\n\x0fLoadDataReponse\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04jsDF\x18\x03 \x01(\x0c\"&\n\x14PredictSymbolRequest\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"_\n\x15PredictSymbolResponse\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\tlast_ohlc\x18\x03 \x03(\t\x12\x14\n\x0cpredict_ohlc\x18\x04 \x01(\t\x12\r\n\x05ptime\x18\x05 \x01(\t\"/\n\x10TimerTaskRequest\x12\x0e\n\x06taskid\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xt\x18\x03 \x01(\t\".\n\x11TimerTaskResponse\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"4\n\x14GetSymbolOhlcRequest\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"5\n\x15GetSymbolOhlcResponse\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04ohlc\x18\x03 \x01(\t2\xe7\x02\n\x04\x44\x61ta\x12?\n\tFetchData\x12\x17.proto.FetchDataRequest\x1a\x17.proto.FetchDataReponse\"\x00\x12<\n\x08LoadData\x12\x16.proto.LoadDataRequest\x1a\x16.proto.LoadDataReponse\"\x00\x12@\n\tTimerTask\x12\x17.proto.TimerTaskRequest\x1a\x18.proto.TimerTaskResponse\"\x00\x12L\n\rGetSymbolOhlc\x12\x1b.proto.GetSymbolOhlcRequest\x1a\x1c.proto.GetSymbolOhlcResponse\"\x00\x12P\n\rPredictSymbol\x12\x1b.proto.PredictSymbolRequest\x1a\x1c.proto.PredictSymbolResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_FETCHDATAREQUEST = _descriptor.Descriptor(
  name='FetchDataRequest',
  full_name='proto.FetchDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbols', full_name='proto.FetchDataRequest.symbols', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='proto.FetchDataRequest.start', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='proto.FetchDataRequest.end', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=84,
)


_FETCHDATAREPONSE = _descriptor.Descriptor(
  name='FetchDataReponse',
  full_name='proto.FetchDataReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.FetchDataReponse.code', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=118,
)


_LOADDATAREQUEST = _descriptor.Descriptor(
  name='LoadDataRequest',
  full_name='proto.LoadDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.LoadDataRequest.symbol', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='proto.LoadDataRequest.start', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='proto.LoadDataRequest.end', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar_type', full_name='proto.LoadDataRequest.bar_type', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=199,
)


_LOADDATAREPONSE = _descriptor.Descriptor(
  name='LoadDataReponse',
  full_name='proto.LoadDataReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.LoadDataReponse.symbol', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jsDF', full_name='proto.LoadDataReponse.jsDF', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=248,
)


_PREDICTSYMBOLREQUEST = _descriptor.Descriptor(
  name='PredictSymbolRequest',
  full_name='proto.PredictSymbolRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.PredictSymbolRequest.symbol', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=288,
)


_PREDICTSYMBOLRESPONSE = _descriptor.Descriptor(
  name='PredictSymbolResponse',
  full_name='proto.PredictSymbolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.PredictSymbolResponse.symbol', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_ohlc', full_name='proto.PredictSymbolResponse.last_ohlc', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predict_ohlc', full_name='proto.PredictSymbolResponse.predict_ohlc', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptime', full_name='proto.PredictSymbolResponse.ptime', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=385,
)


_TIMERTASKREQUEST = _descriptor.Descriptor(
  name='TimerTaskRequest',
  full_name='proto.TimerTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskid', full_name='proto.TimerTaskRequest.taskid', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ext', full_name='proto.TimerTaskRequest.ext', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=434,
)


_TIMERTASKRESPONSE = _descriptor.Descriptor(
  name='TimerTaskResponse',
  full_name='proto.TimerTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.TimerTaskResponse.code', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.TimerTaskResponse.msg', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=482,
)


_GETSYMBOLOHLCREQUEST = _descriptor.Descriptor(
  name='GetSymbolOhlcRequest',
  full_name='proto.GetSymbolOhlcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.GetSymbolOhlcRequest.symbol', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='proto.GetSymbolOhlcRequest.date', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=536,
)


_GETSYMBOLOHLCRESPONSE = _descriptor.Descriptor(
  name='GetSymbolOhlcResponse',
  full_name='proto.GetSymbolOhlcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.GetSymbolOhlcResponse.symbol', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ohlc', full_name='proto.GetSymbolOhlcResponse.ohlc', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=591,
)

DESCRIPTOR.message_types_by_name['FetchDataRequest'] = _FETCHDATAREQUEST
DESCRIPTOR.message_types_by_name['FetchDataReponse'] = _FETCHDATAREPONSE
DESCRIPTOR.message_types_by_name['LoadDataRequest'] = _LOADDATAREQUEST
DESCRIPTOR.message_types_by_name['LoadDataReponse'] = _LOADDATAREPONSE
DESCRIPTOR.message_types_by_name['PredictSymbolRequest'] = _PREDICTSYMBOLREQUEST
DESCRIPTOR.message_types_by_name['PredictSymbolResponse'] = _PREDICTSYMBOLRESPONSE
DESCRIPTOR.message_types_by_name['TimerTaskRequest'] = _TIMERTASKREQUEST
DESCRIPTOR.message_types_by_name['TimerTaskResponse'] = _TIMERTASKRESPONSE
DESCRIPTOR.message_types_by_name['GetSymbolOhlcRequest'] = _GETSYMBOLOHLCREQUEST
DESCRIPTOR.message_types_by_name['GetSymbolOhlcResponse'] = _GETSYMBOLOHLCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchDataRequest = _reflection.GeneratedProtocolMessageType('FetchDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHDATAREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.FetchDataRequest)
  ))
_sym_db.RegisterMessage(FetchDataRequest)

FetchDataReponse = _reflection.GeneratedProtocolMessageType('FetchDataReponse', (_message.Message,), dict(
  DESCRIPTOR = _FETCHDATAREPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.FetchDataReponse)
  ))
_sym_db.RegisterMessage(FetchDataReponse)

LoadDataRequest = _reflection.GeneratedProtocolMessageType('LoadDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADDATAREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.LoadDataRequest)
  ))
_sym_db.RegisterMessage(LoadDataRequest)

LoadDataReponse = _reflection.GeneratedProtocolMessageType('LoadDataReponse', (_message.Message,), dict(
  DESCRIPTOR = _LOADDATAREPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.LoadDataReponse)
  ))
_sym_db.RegisterMessage(LoadDataReponse)

PredictSymbolRequest = _reflection.GeneratedProtocolMessageType('PredictSymbolRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTSYMBOLREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.PredictSymbolRequest)
  ))
_sym_db.RegisterMessage(PredictSymbolRequest)

PredictSymbolResponse = _reflection.GeneratedProtocolMessageType('PredictSymbolResponse', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTSYMBOLRESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.PredictSymbolResponse)
  ))
_sym_db.RegisterMessage(PredictSymbolResponse)

TimerTaskRequest = _reflection.GeneratedProtocolMessageType('TimerTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMERTASKREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.TimerTaskRequest)
  ))
_sym_db.RegisterMessage(TimerTaskRequest)

TimerTaskResponse = _reflection.GeneratedProtocolMessageType('TimerTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _TIMERTASKRESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.TimerTaskResponse)
  ))
_sym_db.RegisterMessage(TimerTaskResponse)

GetSymbolOhlcRequest = _reflection.GeneratedProtocolMessageType('GetSymbolOhlcRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSYMBOLOHLCREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetSymbolOhlcRequest)
  ))
_sym_db.RegisterMessage(GetSymbolOhlcRequest)

GetSymbolOhlcResponse = _reflection.GeneratedProtocolMessageType('GetSymbolOhlcResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSYMBOLOHLCRESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetSymbolOhlcResponse)
  ))
_sym_db.RegisterMessage(GetSymbolOhlcResponse)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='proto.Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=594,
  serialized_end=953,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchData',
    full_name='proto.Data.FetchData',
    index=0,
    containing_service=None,
    input_type=_FETCHDATAREQUEST,
    output_type=_FETCHDATAREPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadData',
    full_name='proto.Data.LoadData',
    index=1,
    containing_service=None,
    input_type=_LOADDATAREQUEST,
    output_type=_LOADDATAREPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TimerTask',
    full_name='proto.Data.TimerTask',
    index=2,
    containing_service=None,
    input_type=_TIMERTASKREQUEST,
    output_type=_TIMERTASKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSymbolOhlc',
    full_name='proto.Data.GetSymbolOhlc',
    index=3,
    containing_service=None,
    input_type=_GETSYMBOLOHLCREQUEST,
    output_type=_GETSYMBOLOHLCRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PredictSymbol',
    full_name='proto.Data.PredictSymbol',
    index=4,
    containing_service=None,
    input_type=_PREDICTSYMBOLREQUEST,
    output_type=_PREDICTSYMBOLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
