// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bridge.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BrgPredictRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ktype                string   `protobuf:"bytes,2,opt,name=ktype,proto3" json:"ktype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrgPredictRequest) Reset()         { *m = BrgPredictRequest{} }
func (m *BrgPredictRequest) String() string { return proto.CompactTextString(m) }
func (*BrgPredictRequest) ProtoMessage()    {}
func (*BrgPredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3ed31acb30cd14, []int{0}
}

func (m *BrgPredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrgPredictRequest.Unmarshal(m, b)
}
func (m *BrgPredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrgPredictRequest.Marshal(b, m, deterministic)
}
func (m *BrgPredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrgPredictRequest.Merge(m, src)
}
func (m *BrgPredictRequest) XXX_Size() int {
	return xxx_messageInfo_BrgPredictRequest.Size(m)
}
func (m *BrgPredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrgPredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrgPredictRequest proto.InternalMessageInfo

func (m *BrgPredictRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *BrgPredictRequest) GetKtype() string {
	if m != nil {
		return m.Ktype
	}
	return ""
}

type BrgPredictResponse struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ktype                string   `protobuf:"bytes,2,opt,name=ktype,proto3" json:"ktype,omitempty"`
	JsRes                string   `protobuf:"bytes,3,opt,name=js_res,json=jsRes,proto3" json:"js_res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrgPredictResponse) Reset()         { *m = BrgPredictResponse{} }
func (m *BrgPredictResponse) String() string { return proto.CompactTextString(m) }
func (*BrgPredictResponse) ProtoMessage()    {}
func (*BrgPredictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3ed31acb30cd14, []int{1}
}

func (m *BrgPredictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrgPredictResponse.Unmarshal(m, b)
}
func (m *BrgPredictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrgPredictResponse.Marshal(b, m, deterministic)
}
func (m *BrgPredictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrgPredictResponse.Merge(m, src)
}
func (m *BrgPredictResponse) XXX_Size() int {
	return xxx_messageInfo_BrgPredictResponse.Size(m)
}
func (m *BrgPredictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrgPredictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrgPredictResponse proto.InternalMessageInfo

func (m *BrgPredictResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *BrgPredictResponse) GetKtype() string {
	if m != nil {
		return m.Ktype
	}
	return ""
}

func (m *BrgPredictResponse) GetJsRes() string {
	if m != nil {
		return m.JsRes
	}
	return ""
}

type BrgHedgeRequest struct {
	Bsymbol              string   `protobuf:"bytes,1,opt,name=bsymbol,proto3" json:"bsymbol,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Ktype                string   `protobuf:"bytes,3,opt,name=ktype,proto3" json:"ktype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrgHedgeRequest) Reset()         { *m = BrgHedgeRequest{} }
func (m *BrgHedgeRequest) String() string { return proto.CompactTextString(m) }
func (*BrgHedgeRequest) ProtoMessage()    {}
func (*BrgHedgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3ed31acb30cd14, []int{2}
}

func (m *BrgHedgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrgHedgeRequest.Unmarshal(m, b)
}
func (m *BrgHedgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrgHedgeRequest.Marshal(b, m, deterministic)
}
func (m *BrgHedgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrgHedgeRequest.Merge(m, src)
}
func (m *BrgHedgeRequest) XXX_Size() int {
	return xxx_messageInfo_BrgHedgeRequest.Size(m)
}
func (m *BrgHedgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrgHedgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrgHedgeRequest proto.InternalMessageInfo

func (m *BrgHedgeRequest) GetBsymbol() string {
	if m != nil {
		return m.Bsymbol
	}
	return ""
}

func (m *BrgHedgeRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *BrgHedgeRequest) GetKtype() string {
	if m != nil {
		return m.Ktype
	}
	return ""
}

type BrgHedgeResponse struct {
	Bsymbol              string   `protobuf:"bytes,1,opt,name=bsymbol,proto3" json:"bsymbol,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Ktype                string   `protobuf:"bytes,3,opt,name=ktype,proto3" json:"ktype,omitempty"`
	JsRes                string   `protobuf:"bytes,4,opt,name=js_res,json=jsRes,proto3" json:"js_res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrgHedgeResponse) Reset()         { *m = BrgHedgeResponse{} }
func (m *BrgHedgeResponse) String() string { return proto.CompactTextString(m) }
func (*BrgHedgeResponse) ProtoMessage()    {}
func (*BrgHedgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3ed31acb30cd14, []int{3}
}

func (m *BrgHedgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrgHedgeResponse.Unmarshal(m, b)
}
func (m *BrgHedgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrgHedgeResponse.Marshal(b, m, deterministic)
}
func (m *BrgHedgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrgHedgeResponse.Merge(m, src)
}
func (m *BrgHedgeResponse) XXX_Size() int {
	return xxx_messageInfo_BrgHedgeResponse.Size(m)
}
func (m *BrgHedgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrgHedgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrgHedgeResponse proto.InternalMessageInfo

func (m *BrgHedgeResponse) GetBsymbol() string {
	if m != nil {
		return m.Bsymbol
	}
	return ""
}

func (m *BrgHedgeResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *BrgHedgeResponse) GetKtype() string {
	if m != nil {
		return m.Ktype
	}
	return ""
}

func (m *BrgHedgeResponse) GetJsRes() string {
	if m != nil {
		return m.JsRes
	}
	return ""
}

type TransFileRequest struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Context              []byte   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransFileRequest) Reset()         { *m = TransFileRequest{} }
func (m *TransFileRequest) String() string { return proto.CompactTextString(m) }
func (*TransFileRequest) ProtoMessage()    {}
func (*TransFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3ed31acb30cd14, []int{4}
}

func (m *TransFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransFileRequest.Unmarshal(m, b)
}
func (m *TransFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransFileRequest.Marshal(b, m, deterministic)
}
func (m *TransFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransFileRequest.Merge(m, src)
}
func (m *TransFileRequest) XXX_Size() int {
	return xxx_messageInfo_TransFileRequest.Size(m)
}
func (m *TransFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransFileRequest proto.InternalMessageInfo

func (m *TransFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransFileRequest) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

type TransFileResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransFileResponse) Reset()         { *m = TransFileResponse{} }
func (m *TransFileResponse) String() string { return proto.CompactTextString(m) }
func (*TransFileResponse) ProtoMessage()    {}
func (*TransFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3ed31acb30cd14, []int{5}
}

func (m *TransFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransFileResponse.Unmarshal(m, b)
}
func (m *TransFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransFileResponse.Marshal(b, m, deterministic)
}
func (m *TransFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransFileResponse.Merge(m, src)
}
func (m *TransFileResponse) XXX_Size() int {
	return xxx_messageInfo_TransFileResponse.Size(m)
}
func (m *TransFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransFileResponse proto.InternalMessageInfo

func (m *TransFileResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*BrgPredictRequest)(nil), "proto.BrgPredictRequest")
	proto.RegisterType((*BrgPredictResponse)(nil), "proto.BrgPredictResponse")
	proto.RegisterType((*BrgHedgeRequest)(nil), "proto.BrgHedgeRequest")
	proto.RegisterType((*BrgHedgeResponse)(nil), "proto.BrgHedgeResponse")
	proto.RegisterType((*TransFileRequest)(nil), "proto.TransFileRequest")
	proto.RegisterType((*TransFileResponse)(nil), "proto.TransFileResponse")
}

func init() { proto.RegisterFile("bridge.proto", fileDescriptor_1d3ed31acb30cd14) }

var fileDescriptor_1d3ed31acb30cd14 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0xfd, 0xb7, 0x8d, 0x76, 0x28, 0x98, 0x0e, 0x5a, 0xd7, 0x9c, 0x24, 0x20, 0x78,
	0xea, 0x41, 0xcf, 0x42, 0xad, 0x20, 0x1e, 0x25, 0x08, 0xe2, 0x49, 0x9a, 0x64, 0x08, 0xa9, 0x4d,
	0x36, 0xee, 0xac, 0x60, 0xbf, 0xa4, 0x9f, 0x49, 0xb2, 0xc9, 0x26, 0x69, 0xeb, 0x45, 0xf0, 0x94,
	0x7d, 0x33, 0xe1, 0xb7, 0xef, 0xcd, 0x2c, 0x8c, 0x43, 0x95, 0xc6, 0x09, 0xcd, 0x0a, 0x25, 0xb5,
	0xc4, 0xa1, 0xf9, 0xf8, 0xb7, 0x30, 0x59, 0xa8, 0xe4, 0x51, 0x51, 0x9c, 0x46, 0x3a, 0xa0, 0xf7,
	0x0f, 0x62, 0x8d, 0x53, 0x70, 0x78, 0x93, 0x85, 0x72, 0x2d, 0x7a, 0xe7, 0xbd, 0xcb, 0x51, 0x50,
	0x2b, 0x3c, 0x86, 0xe1, 0x9b, 0xde, 0x14, 0x24, 0xfe, 0x9b, 0x72, 0x25, 0xfc, 0x17, 0xc0, 0x2e,
	0x82, 0x0b, 0x99, 0x33, 0xfd, 0x8e, 0x81, 0x27, 0xe0, 0xac, 0xf8, 0x55, 0x11, 0x8b, 0x7e, 0x55,
	0x5e, 0x71, 0x40, 0xec, 0x3f, 0xc3, 0xd1, 0x42, 0x25, 0x0f, 0x14, 0x27, 0x64, 0xbd, 0x09, 0x38,
	0x08, 0xb7, 0xc0, 0x56, 0x96, 0x64, 0x8e, 0x64, 0x4b, 0x36, 0xa2, 0xbd, 0xaf, 0xdf, 0xf5, 0x2c,
	0xc1, 0x6d, 0xc1, 0xb5, 0xe3, 0x3f, 0x21, 0x77, 0x92, 0x0c, 0xba, 0x49, 0xe6, 0xe0, 0x3e, 0xa9,
	0x65, 0xce, 0xf7, 0xe9, 0xba, 0x89, 0x82, 0x30, 0xc8, 0x97, 0x99, 0xa5, 0x9a, 0x73, 0x69, 0x22,
	0x92, 0xb9, 0xa6, 0x4f, 0x6d, 0xb0, 0xe3, 0xc0, 0x4a, 0xff, 0x02, 0x26, 0x1d, 0x42, 0xed, 0xd9,
	0x85, 0x7e, 0xc6, 0x49, 0xed, 0xb7, 0x3c, 0x5e, 0x7d, 0xf5, 0xc0, 0xa9, 0x16, 0x8d, 0x37, 0x70,
	0x68, 0x43, 0xe2, 0xb4, 0x5a, 0xfb, 0x6c, 0x67, 0x9c, 0xde, 0xe9, 0x5e, 0xbd, 0x22, 0xfb, 0xff,
	0xf0, 0x0e, 0xa0, 0xdd, 0x2b, 0x8a, 0xf6, 0xc7, 0xed, 0xd7, 0xe2, 0x9d, 0xfd, 0xd0, 0x69, 0x20,
	0x73, 0x18, 0x35, 0xae, 0xd1, 0x5e, 0xb6, 0x3b, 0x09, 0x4f, 0xec, 0x37, 0x2c, 0x21, 0x74, 0x4c,
	0xeb, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xad, 0x3f, 0x87, 0x5f, 0xbf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BridgeClient interface {
	BrgHedge(ctx context.Context, in *BrgHedgeRequest, opts ...grpc.CallOption) (*BrgHedgeResponse, error)
	BrgPredict(ctx context.Context, in *BrgPredictRequest, opts ...grpc.CallOption) (*BrgPredictResponse, error)
	TransFile(ctx context.Context, in *TransFileRequest, opts ...grpc.CallOption) (*TransFileResponse, error)
}

type bridgeClient struct {
	cc *grpc.ClientConn
}

func NewBridgeClient(cc *grpc.ClientConn) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) BrgHedge(ctx context.Context, in *BrgHedgeRequest, opts ...grpc.CallOption) (*BrgHedgeResponse, error) {
	out := new(BrgHedgeResponse)
	err := c.cc.Invoke(ctx, "/proto.bridge/BrgHedge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) BrgPredict(ctx context.Context, in *BrgPredictRequest, opts ...grpc.CallOption) (*BrgPredictResponse, error) {
	out := new(BrgPredictResponse)
	err := c.cc.Invoke(ctx, "/proto.bridge/BrgPredict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) TransFile(ctx context.Context, in *TransFileRequest, opts ...grpc.CallOption) (*TransFileResponse, error) {
	out := new(TransFileResponse)
	err := c.cc.Invoke(ctx, "/proto.bridge/TransFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServer is the server API for Bridge service.
type BridgeServer interface {
	BrgHedge(context.Context, *BrgHedgeRequest) (*BrgHedgeResponse, error)
	BrgPredict(context.Context, *BrgPredictRequest) (*BrgPredictResponse, error)
	TransFile(context.Context, *TransFileRequest) (*TransFileResponse, error)
}

// UnimplementedBridgeServer can be embedded to have forward compatible implementations.
type UnimplementedBridgeServer struct {
}

func (*UnimplementedBridgeServer) BrgHedge(ctx context.Context, req *BrgHedgeRequest) (*BrgHedgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrgHedge not implemented")
}
func (*UnimplementedBridgeServer) BrgPredict(ctx context.Context, req *BrgPredictRequest) (*BrgPredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrgPredict not implemented")
}
func (*UnimplementedBridgeServer) TransFile(ctx context.Context, req *TransFileRequest) (*TransFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransFile not implemented")
}

func RegisterBridgeServer(s *grpc.Server, srv BridgeServer) {
	s.RegisterService(&_Bridge_serviceDesc, srv)
}

func _Bridge_BrgHedge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrgHedgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).BrgHedge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.bridge/BrgHedge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).BrgHedge(ctx, req.(*BrgHedgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_BrgPredict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrgPredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).BrgPredict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.bridge/BrgPredict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).BrgPredict(ctx, req.(*BrgPredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_TransFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).TransFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.bridge/TransFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).TransFile(ctx, req.(*TransFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bridge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BrgHedge",
			Handler:    _Bridge_BrgHedge_Handler,
		},
		{
			MethodName: "BrgPredict",
			Handler:    _Bridge_BrgPredict_Handler,
		},
		{
			MethodName: "TransFile",
			Handler:    _Bridge_TransFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge.proto",
}
