# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bridge_pb2 as bridge__pb2


class bridgeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BrgHedge = channel.unary_unary(
        '/proto.bridge/BrgHedge',
        request_serializer=bridge__pb2.BrgHedgeRequest.SerializeToString,
        response_deserializer=bridge__pb2.BrgHedgeResponse.FromString,
        )
    self.BrgPredict = channel.unary_unary(
        '/proto.bridge/BrgPredict',
        request_serializer=bridge__pb2.BrgPredictRequest.SerializeToString,
        response_deserializer=bridge__pb2.BrgPredictResponse.FromString,
        )
    self.TransFile = channel.unary_unary(
        '/proto.bridge/TransFile',
        request_serializer=bridge__pb2.TransFileRequest.SerializeToString,
        response_deserializer=bridge__pb2.TransFileResponse.FromString,
        )


class bridgeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BrgHedge(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BrgPredict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_bridgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BrgHedge': grpc.unary_unary_rpc_method_handler(
          servicer.BrgHedge,
          request_deserializer=bridge__pb2.BrgHedgeRequest.FromString,
          response_serializer=bridge__pb2.BrgHedgeResponse.SerializeToString,
      ),
      'BrgPredict': grpc.unary_unary_rpc_method_handler(
          servicer.BrgPredict,
          request_deserializer=bridge__pb2.BrgPredictRequest.FromString,
          response_serializer=bridge__pb2.BrgPredictResponse.SerializeToString,
      ),
      'TransFile': grpc.unary_unary_rpc_method_handler(
          servicer.TransFile,
          request_deserializer=bridge__pb2.TransFileRequest.FromString,
          response_serializer=bridge__pb2.TransFileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.bridge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
