# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bridge.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x62ridge.proto\x12\x05proto\"2\n\x11\x42rgPredictRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05ktype\x18\x02 \x01(\t\"C\n\x12\x42rgPredictResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05ktype\x18\x02 \x01(\t\x12\x0e\n\x06js_res\x18\x03 \x01(\t\"@\n\x0f\x42rgHedgeRequest\x12\x0f\n\x07\x62symbol\x18\x01 \x01(\t\x12\r\n\x05scope\x18\x02 \x01(\t\x12\r\n\x05ktype\x18\x03 \x01(\t\"Q\n\x10\x42rgHedgeResponse\x12\x0f\n\x07\x62symbol\x18\x01 \x01(\t\x12\r\n\x05scope\x18\x02 \x01(\t\x12\r\n\x05ktype\x18\x03 \x01(\t\x12\x0e\n\x06js_res\x18\x04 \x01(\t\"1\n\x10TransFileRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\x0c\" \n\x11TransFileResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xce\x01\n\x06\x62ridge\x12=\n\x08\x42rgHedge\x12\x16.proto.BrgHedgeRequest\x1a\x17.proto.BrgHedgeResponse\"\x00\x12\x43\n\nBrgPredict\x12\x18.proto.BrgPredictRequest\x1a\x19.proto.BrgPredictResponse\"\x00\x12@\n\tTransFile\x12\x17.proto.TransFileRequest\x1a\x18.proto.TransFileResponse\"\x00\x62\x06proto3')
)




_BRGPREDICTREQUEST = _descriptor.Descriptor(
  name='BrgPredictRequest',
  full_name='proto.BrgPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.BrgPredictRequest.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ktype', full_name='proto.BrgPredictRequest.ktype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=73,
)


_BRGPREDICTRESPONSE = _descriptor.Descriptor(
  name='BrgPredictResponse',
  full_name='proto.BrgPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='proto.BrgPredictResponse.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ktype', full_name='proto.BrgPredictResponse.ktype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='js_res', full_name='proto.BrgPredictResponse.js_res', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=142,
)


_BRGHEDGEREQUEST = _descriptor.Descriptor(
  name='BrgHedgeRequest',
  full_name='proto.BrgHedgeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bsymbol', full_name='proto.BrgHedgeRequest.bsymbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='proto.BrgHedgeRequest.scope', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ktype', full_name='proto.BrgHedgeRequest.ktype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=208,
)


_BRGHEDGERESPONSE = _descriptor.Descriptor(
  name='BrgHedgeResponse',
  full_name='proto.BrgHedgeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bsymbol', full_name='proto.BrgHedgeResponse.bsymbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='proto.BrgHedgeResponse.scope', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ktype', full_name='proto.BrgHedgeResponse.ktype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='js_res', full_name='proto.BrgHedgeResponse.js_res', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=291,
)


_TRANSFILEREQUEST = _descriptor.Descriptor(
  name='TransFileRequest',
  full_name='proto.TransFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.TransFileRequest.name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='proto.TransFileRequest.context', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=342,
)


_TRANSFILERESPONSE = _descriptor.Descriptor(
  name='TransFileResponse',
  full_name='proto.TransFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.TransFileResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=376,
)

DESCRIPTOR.message_types_by_name['BrgPredictRequest'] = _BRGPREDICTREQUEST
DESCRIPTOR.message_types_by_name['BrgPredictResponse'] = _BRGPREDICTRESPONSE
DESCRIPTOR.message_types_by_name['BrgHedgeRequest'] = _BRGHEDGEREQUEST
DESCRIPTOR.message_types_by_name['BrgHedgeResponse'] = _BRGHEDGERESPONSE
DESCRIPTOR.message_types_by_name['TransFileRequest'] = _TRANSFILEREQUEST
DESCRIPTOR.message_types_by_name['TransFileResponse'] = _TRANSFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrgPredictRequest = _reflection.GeneratedProtocolMessageType('BrgPredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _BRGPREDICTREQUEST,
  __module__ = 'bridge_pb2'
  # @@protoc_insertion_point(class_scope:proto.BrgPredictRequest)
  ))
_sym_db.RegisterMessage(BrgPredictRequest)

BrgPredictResponse = _reflection.GeneratedProtocolMessageType('BrgPredictResponse', (_message.Message,), dict(
  DESCRIPTOR = _BRGPREDICTRESPONSE,
  __module__ = 'bridge_pb2'
  # @@protoc_insertion_point(class_scope:proto.BrgPredictResponse)
  ))
_sym_db.RegisterMessage(BrgPredictResponse)

BrgHedgeRequest = _reflection.GeneratedProtocolMessageType('BrgHedgeRequest', (_message.Message,), dict(
  DESCRIPTOR = _BRGHEDGEREQUEST,
  __module__ = 'bridge_pb2'
  # @@protoc_insertion_point(class_scope:proto.BrgHedgeRequest)
  ))
_sym_db.RegisterMessage(BrgHedgeRequest)

BrgHedgeResponse = _reflection.GeneratedProtocolMessageType('BrgHedgeResponse', (_message.Message,), dict(
  DESCRIPTOR = _BRGHEDGERESPONSE,
  __module__ = 'bridge_pb2'
  # @@protoc_insertion_point(class_scope:proto.BrgHedgeResponse)
  ))
_sym_db.RegisterMessage(BrgHedgeResponse)

TransFileRequest = _reflection.GeneratedProtocolMessageType('TransFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFILEREQUEST,
  __module__ = 'bridge_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransFileRequest)
  ))
_sym_db.RegisterMessage(TransFileRequest)

TransFileResponse = _reflection.GeneratedProtocolMessageType('TransFileResponse', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFILERESPONSE,
  __module__ = 'bridge_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransFileResponse)
  ))
_sym_db.RegisterMessage(TransFileResponse)



_BRIDGE = _descriptor.ServiceDescriptor(
  name='bridge',
  full_name='proto.bridge',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=379,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='BrgHedge',
    full_name='proto.bridge.BrgHedge',
    index=0,
    containing_service=None,
    input_type=_BRGHEDGEREQUEST,
    output_type=_BRGHEDGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BrgPredict',
    full_name='proto.bridge.BrgPredict',
    index=1,
    containing_service=None,
    input_type=_BRGPREDICTREQUEST,
    output_type=_BRGPREDICTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransFile',
    full_name='proto.bridge.TransFile',
    index=2,
    containing_service=None,
    input_type=_TRANSFILEREQUEST,
    output_type=_TRANSFILERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRIDGE)

DESCRIPTOR.services_by_name['bridge'] = _BRIDGE

# @@protoc_insertion_point(module_scope)
