// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/////////////////////////////for org/////////////////
type OrgRegistRequest struct {
	// Types that are valid to be assigned to Id:
	//	*OrgRegistRequest_Phone
	//	*OrgRegistRequest_Email
	Id isOrgRegistRequest_Id `protobuf_oneof:"id"`
	// Types that are valid to be assigned to Verify:
	//	*OrgRegistRequest_Pswd
	//	*OrgRegistRequest_VerifyCode
	Verify               isOrgRegistRequest_Verify `protobuf_oneof:"verify"`
	OrgInfo              []byte                    `protobuf:"bytes,6,opt,name=org_info,json=orgInfo,proto3" json:"org_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OrgRegistRequest) Reset()         { *m = OrgRegistRequest{} }
func (m *OrgRegistRequest) String() string { return proto.CompactTextString(m) }
func (*OrgRegistRequest) ProtoMessage()    {}
func (*OrgRegistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *OrgRegistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgRegistRequest.Unmarshal(m, b)
}
func (m *OrgRegistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgRegistRequest.Marshal(b, m, deterministic)
}
func (m *OrgRegistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgRegistRequest.Merge(m, src)
}
func (m *OrgRegistRequest) XXX_Size() int {
	return xxx_messageInfo_OrgRegistRequest.Size(m)
}
func (m *OrgRegistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgRegistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrgRegistRequest proto.InternalMessageInfo

type isOrgRegistRequest_Id interface {
	isOrgRegistRequest_Id()
}

type OrgRegistRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type OrgRegistRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*OrgRegistRequest_Phone) isOrgRegistRequest_Id() {}

func (*OrgRegistRequest_Email) isOrgRegistRequest_Id() {}

func (m *OrgRegistRequest) GetId() isOrgRegistRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OrgRegistRequest) GetPhone() string {
	if x, ok := m.GetId().(*OrgRegistRequest_Phone); ok {
		return x.Phone
	}
	return ""
}

func (m *OrgRegistRequest) GetEmail() string {
	if x, ok := m.GetId().(*OrgRegistRequest_Email); ok {
		return x.Email
	}
	return ""
}

type isOrgRegistRequest_Verify interface {
	isOrgRegistRequest_Verify()
}

type OrgRegistRequest_Pswd struct {
	Pswd string `protobuf:"bytes,4,opt,name=pswd,proto3,oneof"`
}

type OrgRegistRequest_VerifyCode struct {
	VerifyCode string `protobuf:"bytes,5,opt,name=verify_code,json=verifyCode,proto3,oneof"`
}

func (*OrgRegistRequest_Pswd) isOrgRegistRequest_Verify() {}

func (*OrgRegistRequest_VerifyCode) isOrgRegistRequest_Verify() {}

func (m *OrgRegistRequest) GetVerify() isOrgRegistRequest_Verify {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *OrgRegistRequest) GetPswd() string {
	if x, ok := m.GetVerify().(*OrgRegistRequest_Pswd); ok {
		return x.Pswd
	}
	return ""
}

func (m *OrgRegistRequest) GetVerifyCode() string {
	if x, ok := m.GetVerify().(*OrgRegistRequest_VerifyCode); ok {
		return x.VerifyCode
	}
	return ""
}

func (m *OrgRegistRequest) GetOrgInfo() []byte {
	if m != nil {
		return m.OrgInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OrgRegistRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OrgRegistRequest_Phone)(nil),
		(*OrgRegistRequest_Email)(nil),
		(*OrgRegistRequest_Pswd)(nil),
		(*OrgRegistRequest_VerifyCode)(nil),
	}
}

type OrgRegistResponse struct {
	Oid                  uint64   `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	OrgInfo              []byte   `protobuf:"bytes,6,opt,name=org_info,json=orgInfo,proto3" json:"org_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgRegistResponse) Reset()         { *m = OrgRegistResponse{} }
func (m *OrgRegistResponse) String() string { return proto.CompactTextString(m) }
func (*OrgRegistResponse) ProtoMessage()    {}
func (*OrgRegistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *OrgRegistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgRegistResponse.Unmarshal(m, b)
}
func (m *OrgRegistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgRegistResponse.Marshal(b, m, deterministic)
}
func (m *OrgRegistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgRegistResponse.Merge(m, src)
}
func (m *OrgRegistResponse) XXX_Size() int {
	return xxx_messageInfo_OrgRegistResponse.Size(m)
}
func (m *OrgRegistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgRegistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrgRegistResponse proto.InternalMessageInfo

func (m *OrgRegistResponse) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *OrgRegistResponse) GetOrgInfo() []byte {
	if m != nil {
		return m.OrgInfo
	}
	return nil
}

type OrgLoginRequest struct {
	// Types that are valid to be assigned to Id:
	//	*OrgLoginRequest_Phone
	//	*OrgLoginRequest_Email
	//	*OrgLoginRequest_Oid
	Id isOrgLoginRequest_Id `protobuf_oneof:"id"`
	// Types that are valid to be assigned to Verify:
	//	*OrgLoginRequest_Pswd
	//	*OrgLoginRequest_VerifyCode
	Verify               isOrgLoginRequest_Verify `protobuf_oneof:"verify"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrgLoginRequest) Reset()         { *m = OrgLoginRequest{} }
func (m *OrgLoginRequest) String() string { return proto.CompactTextString(m) }
func (*OrgLoginRequest) ProtoMessage()    {}
func (*OrgLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *OrgLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgLoginRequest.Unmarshal(m, b)
}
func (m *OrgLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgLoginRequest.Marshal(b, m, deterministic)
}
func (m *OrgLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgLoginRequest.Merge(m, src)
}
func (m *OrgLoginRequest) XXX_Size() int {
	return xxx_messageInfo_OrgLoginRequest.Size(m)
}
func (m *OrgLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrgLoginRequest proto.InternalMessageInfo

type isOrgLoginRequest_Id interface {
	isOrgLoginRequest_Id()
}

type OrgLoginRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type OrgLoginRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type OrgLoginRequest_Oid struct {
	Oid uint64 `protobuf:"varint,4,opt,name=oid,proto3,oneof"`
}

func (*OrgLoginRequest_Phone) isOrgLoginRequest_Id() {}

func (*OrgLoginRequest_Email) isOrgLoginRequest_Id() {}

func (*OrgLoginRequest_Oid) isOrgLoginRequest_Id() {}

func (m *OrgLoginRequest) GetId() isOrgLoginRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OrgLoginRequest) GetPhone() string {
	if x, ok := m.GetId().(*OrgLoginRequest_Phone); ok {
		return x.Phone
	}
	return ""
}

func (m *OrgLoginRequest) GetEmail() string {
	if x, ok := m.GetId().(*OrgLoginRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (m *OrgLoginRequest) GetOid() uint64 {
	if x, ok := m.GetId().(*OrgLoginRequest_Oid); ok {
		return x.Oid
	}
	return 0
}

type isOrgLoginRequest_Verify interface {
	isOrgLoginRequest_Verify()
}

type OrgLoginRequest_Pswd struct {
	Pswd string `protobuf:"bytes,7,opt,name=pswd,proto3,oneof"`
}

type OrgLoginRequest_VerifyCode struct {
	VerifyCode string `protobuf:"bytes,8,opt,name=verify_code,json=verifyCode,proto3,oneof"`
}

func (*OrgLoginRequest_Pswd) isOrgLoginRequest_Verify() {}

func (*OrgLoginRequest_VerifyCode) isOrgLoginRequest_Verify() {}

func (m *OrgLoginRequest) GetVerify() isOrgLoginRequest_Verify {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *OrgLoginRequest) GetPswd() string {
	if x, ok := m.GetVerify().(*OrgLoginRequest_Pswd); ok {
		return x.Pswd
	}
	return ""
}

func (m *OrgLoginRequest) GetVerifyCode() string {
	if x, ok := m.GetVerify().(*OrgLoginRequest_VerifyCode); ok {
		return x.VerifyCode
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OrgLoginRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OrgLoginRequest_Phone)(nil),
		(*OrgLoginRequest_Email)(nil),
		(*OrgLoginRequest_Oid)(nil),
		(*OrgLoginRequest_Pswd)(nil),
		(*OrgLoginRequest_VerifyCode)(nil),
	}
}

type OrgLoginResponse struct {
	Oid                  uint64   `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	OrgInfo              []byte   `protobuf:"bytes,3,opt,name=org_info,json=orgInfo,proto3" json:"org_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgLoginResponse) Reset()         { *m = OrgLoginResponse{} }
func (m *OrgLoginResponse) String() string { return proto.CompactTextString(m) }
func (*OrgLoginResponse) ProtoMessage()    {}
func (*OrgLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *OrgLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgLoginResponse.Unmarshal(m, b)
}
func (m *OrgLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgLoginResponse.Marshal(b, m, deterministic)
}
func (m *OrgLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgLoginResponse.Merge(m, src)
}
func (m *OrgLoginResponse) XXX_Size() int {
	return xxx_messageInfo_OrgLoginResponse.Size(m)
}
func (m *OrgLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrgLoginResponse proto.InternalMessageInfo

func (m *OrgLoginResponse) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *OrgLoginResponse) GetOrgInfo() []byte {
	if m != nil {
		return m.OrgInfo
	}
	return nil
}

/////////////////////////////for user//////////////
type RegistRequest struct {
	// Types that are valid to be assigned to Id:
	//	*RegistRequest_Wxcode
	//	*RegistRequest_Phone
	//	*RegistRequest_Email
	Id isRegistRequest_Id `protobuf_oneof:"id"`
	// Types that are valid to be assigned to Verify:
	//	*RegistRequest_Pswd
	//	*RegistRequest_VerifyCode
	Verify               isRegistRequest_Verify `protobuf_oneof:"verify"`
	Channel              uint64                 `protobuf:"varint,6,opt,name=channel,proto3" json:"channel,omitempty"`
	UserInfo             []byte                 `protobuf:"bytes,7,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegistRequest) Reset()         { *m = RegistRequest{} }
func (m *RegistRequest) String() string { return proto.CompactTextString(m) }
func (*RegistRequest) ProtoMessage()    {}
func (*RegistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *RegistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistRequest.Unmarshal(m, b)
}
func (m *RegistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistRequest.Marshal(b, m, deterministic)
}
func (m *RegistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistRequest.Merge(m, src)
}
func (m *RegistRequest) XXX_Size() int {
	return xxx_messageInfo_RegistRequest.Size(m)
}
func (m *RegistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistRequest proto.InternalMessageInfo

type isRegistRequest_Id interface {
	isRegistRequest_Id()
}

type RegistRequest_Wxcode struct {
	Wxcode string `protobuf:"bytes,1,opt,name=wxcode,proto3,oneof"`
}

type RegistRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type RegistRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*RegistRequest_Wxcode) isRegistRequest_Id() {}

func (*RegistRequest_Phone) isRegistRequest_Id() {}

func (*RegistRequest_Email) isRegistRequest_Id() {}

func (m *RegistRequest) GetId() isRegistRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RegistRequest) GetWxcode() string {
	if x, ok := m.GetId().(*RegistRequest_Wxcode); ok {
		return x.Wxcode
	}
	return ""
}

func (m *RegistRequest) GetPhone() string {
	if x, ok := m.GetId().(*RegistRequest_Phone); ok {
		return x.Phone
	}
	return ""
}

func (m *RegistRequest) GetEmail() string {
	if x, ok := m.GetId().(*RegistRequest_Email); ok {
		return x.Email
	}
	return ""
}

type isRegistRequest_Verify interface {
	isRegistRequest_Verify()
}

type RegistRequest_Pswd struct {
	Pswd string `protobuf:"bytes,4,opt,name=pswd,proto3,oneof"`
}

type RegistRequest_VerifyCode struct {
	VerifyCode string `protobuf:"bytes,5,opt,name=verify_code,json=verifyCode,proto3,oneof"`
}

func (*RegistRequest_Pswd) isRegistRequest_Verify() {}

func (*RegistRequest_VerifyCode) isRegistRequest_Verify() {}

func (m *RegistRequest) GetVerify() isRegistRequest_Verify {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *RegistRequest) GetPswd() string {
	if x, ok := m.GetVerify().(*RegistRequest_Pswd); ok {
		return x.Pswd
	}
	return ""
}

func (m *RegistRequest) GetVerifyCode() string {
	if x, ok := m.GetVerify().(*RegistRequest_VerifyCode); ok {
		return x.VerifyCode
	}
	return ""
}

func (m *RegistRequest) GetChannel() uint64 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *RegistRequest) GetUserInfo() []byte {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RegistRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RegistRequest_Wxcode)(nil),
		(*RegistRequest_Phone)(nil),
		(*RegistRequest_Email)(nil),
		(*RegistRequest_Pswd)(nil),
		(*RegistRequest_VerifyCode)(nil),
	}
}

type RegistResponse struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	UserInfo             []byte   `protobuf:"bytes,6,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Slots                []byte   `protobuf:"bytes,7,opt,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistResponse) Reset()         { *m = RegistResponse{} }
func (m *RegistResponse) String() string { return proto.CompactTextString(m) }
func (*RegistResponse) ProtoMessage()    {}
func (*RegistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *RegistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistResponse.Unmarshal(m, b)
}
func (m *RegistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistResponse.Marshal(b, m, deterministic)
}
func (m *RegistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistResponse.Merge(m, src)
}
func (m *RegistResponse) XXX_Size() int {
	return xxx_messageInfo_RegistResponse.Size(m)
}
func (m *RegistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistResponse proto.InternalMessageInfo

func (m *RegistResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RegistResponse) GetUserInfo() []byte {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *RegistResponse) GetSlots() []byte {
	if m != nil {
		return m.Slots
	}
	return nil
}

type LoginRequest struct {
	// Types that are valid to be assigned to Id:
	//	*LoginRequest_Wxcode
	//	*LoginRequest_Phone
	//	*LoginRequest_Email
	//	*LoginRequest_Uid
	Id isLoginRequest_Id `protobuf_oneof:"id"`
	// Types that are valid to be assigned to Verify:
	//	*LoginRequest_Pswd
	//	*LoginRequest_VerifyCode
	Verify               isLoginRequest_Verify `protobuf_oneof:"verify"`
	Channel              uint64                `protobuf:"varint,9,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type isLoginRequest_Id interface {
	isLoginRequest_Id()
}

type LoginRequest_Wxcode struct {
	Wxcode string `protobuf:"bytes,1,opt,name=wxcode,proto3,oneof"`
}

type LoginRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type LoginRequest_Uid struct {
	Uid uint64 `protobuf:"varint,4,opt,name=uid,proto3,oneof"`
}

func (*LoginRequest_Wxcode) isLoginRequest_Id() {}

func (*LoginRequest_Phone) isLoginRequest_Id() {}

func (*LoginRequest_Email) isLoginRequest_Id() {}

func (*LoginRequest_Uid) isLoginRequest_Id() {}

func (m *LoginRequest) GetId() isLoginRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *LoginRequest) GetWxcode() string {
	if x, ok := m.GetId().(*LoginRequest_Wxcode); ok {
		return x.Wxcode
	}
	return ""
}

func (m *LoginRequest) GetPhone() string {
	if x, ok := m.GetId().(*LoginRequest_Phone); ok {
		return x.Phone
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if x, ok := m.GetId().(*LoginRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (m *LoginRequest) GetUid() uint64 {
	if x, ok := m.GetId().(*LoginRequest_Uid); ok {
		return x.Uid
	}
	return 0
}

type isLoginRequest_Verify interface {
	isLoginRequest_Verify()
}

type LoginRequest_Pswd struct {
	Pswd string `protobuf:"bytes,7,opt,name=pswd,proto3,oneof"`
}

type LoginRequest_VerifyCode struct {
	VerifyCode string `protobuf:"bytes,8,opt,name=verify_code,json=verifyCode,proto3,oneof"`
}

func (*LoginRequest_Pswd) isLoginRequest_Verify() {}

func (*LoginRequest_VerifyCode) isLoginRequest_Verify() {}

func (m *LoginRequest) GetVerify() isLoginRequest_Verify {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *LoginRequest) GetPswd() string {
	if x, ok := m.GetVerify().(*LoginRequest_Pswd); ok {
		return x.Pswd
	}
	return ""
}

func (m *LoginRequest) GetVerifyCode() string {
	if x, ok := m.GetVerify().(*LoginRequest_VerifyCode); ok {
		return x.VerifyCode
	}
	return ""
}

func (m *LoginRequest) GetChannel() uint64 {
	if m != nil {
		return m.Channel
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginRequest_Wxcode)(nil),
		(*LoginRequest_Phone)(nil),
		(*LoginRequest_Email)(nil),
		(*LoginRequest_Uid)(nil),
		(*LoginRequest_Pswd)(nil),
		(*LoginRequest_VerifyCode)(nil),
	}
}

type LoginResponse struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	UserInfo             []byte   `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Slots                []byte   `protobuf:"bytes,7,opt,name=slots,proto3" json:"slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginResponse) GetUserInfo() []byte {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *LoginResponse) GetSlots() []byte {
	if m != nil {
		return m.Slots
	}
	return nil
}

type BindPhoneRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Verify               string   `protobuf:"bytes,3,opt,name=verify,proto3" json:"verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindPhoneRequest) Reset()         { *m = BindPhoneRequest{} }
func (m *BindPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*BindPhoneRequest) ProtoMessage()    {}
func (*BindPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *BindPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindPhoneRequest.Unmarshal(m, b)
}
func (m *BindPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindPhoneRequest.Marshal(b, m, deterministic)
}
func (m *BindPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindPhoneRequest.Merge(m, src)
}
func (m *BindPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_BindPhoneRequest.Size(m)
}
func (m *BindPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindPhoneRequest proto.InternalMessageInfo

func (m *BindPhoneRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BindPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *BindPhoneRequest) GetVerify() string {
	if m != nil {
		return m.Verify
	}
	return ""
}

type BindPhoneReponse struct {
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindPhoneReponse) Reset()         { *m = BindPhoneReponse{} }
func (m *BindPhoneReponse) String() string { return proto.CompactTextString(m) }
func (*BindPhoneReponse) ProtoMessage()    {}
func (*BindPhoneReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *BindPhoneReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindPhoneReponse.Unmarshal(m, b)
}
func (m *BindPhoneReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindPhoneReponse.Marshal(b, m, deterministic)
}
func (m *BindPhoneReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindPhoneReponse.Merge(m, src)
}
func (m *BindPhoneReponse) XXX_Size() int {
	return xxx_messageInfo_BindPhoneReponse.Size(m)
}
func (m *BindPhoneReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindPhoneReponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindPhoneReponse proto.InternalMessageInfo

func (m *BindPhoneReponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UpdateInfoRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	UserInfo             []byte   `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfoRequest) Reset()         { *m = UpdateInfoRequest{} }
func (m *UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoRequest) ProtoMessage()    {}
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoRequest.Merge(m, src)
}
func (m *UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoRequest.Size(m)
}
func (m *UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoRequest proto.InternalMessageInfo

func (m *UpdateInfoRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UpdateInfoRequest) GetUserInfo() []byte {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type UpdateInfoResponse struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	UserInfo             []byte   `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfoResponse) Reset()         { *m = UpdateInfoResponse{} }
func (m *UpdateInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoResponse) ProtoMessage()    {}
func (*UpdateInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *UpdateInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoResponse.Unmarshal(m, b)
}
func (m *UpdateInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoResponse.Merge(m, src)
}
func (m *UpdateInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoResponse.Size(m)
}
func (m *UpdateInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoResponse proto.InternalMessageInfo

func (m *UpdateInfoResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UpdateInfoResponse) GetUserInfo() []byte {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*OrgRegistRequest)(nil), "proto.OrgRegistRequest")
	proto.RegisterType((*OrgRegistResponse)(nil), "proto.OrgRegistResponse")
	proto.RegisterType((*OrgLoginRequest)(nil), "proto.OrgLoginRequest")
	proto.RegisterType((*OrgLoginResponse)(nil), "proto.OrgLoginResponse")
	proto.RegisterType((*RegistRequest)(nil), "proto.RegistRequest")
	proto.RegisterType((*RegistResponse)(nil), "proto.RegistResponse")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*BindPhoneRequest)(nil), "proto.BindPhoneRequest")
	proto.RegisterType((*BindPhoneReponse)(nil), "proto.BindPhoneReponse")
	proto.RegisterType((*UpdateInfoRequest)(nil), "proto.UpdateInfoRequest")
	proto.RegisterType((*UpdateInfoResponse)(nil), "proto.UpdateInfoResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x13, 0xc7, 0x1f, 0x43, 0x03, 0xe9, 0x60, 0x5a, 0xd7, 0x5c, 0x8a, 0x4f, 0x39, 0xf5,
	0x00, 0x48, 0x9c, 0x50, 0x4b, 0x72, 0x29, 0x12, 0x52, 0x91, 0x45, 0xcf, 0x55, 0x88, 0x37, 0xee,
	0x4a, 0x61, 0xd7, 0xf8, 0x83, 0xc2, 0x9f, 0xe1, 0xc8, 0xdf, 0xe1, 0xcc, 0xaf, 0x01, 0x79, 0x77,
	0x6d, 0x67, 0xe3, 0x28, 0x8a, 0x0a, 0xe2, 0x94, 0xcc, 0xec, 0xec, 0x9b, 0xf7, 0xde, 0x4c, 0x36,
	0x30, 0x9a, 0x2f, 0x16, 0xbc, 0x64, 0xc5, 0x59, 0x9a, 0xf1, 0x82, 0xe3, 0x50, 0x7c, 0x84, 0x3f,
	0x0c, 0x18, 0x5f, 0x65, 0x49, 0x44, 0x12, 0x9a, 0x17, 0x11, 0xf9, 0x5c, 0x92, 0xbc, 0xc0, 0x23,
	0x18, 0xa6, 0xb7, 0x9c, 0x11, 0xbf, 0x7f, 0x6a, 0x4c, 0xdc, 0xcb, 0x5e, 0x24, 0xc3, 0x2a, 0x4f,
	0x3e, 0xcd, 0xe9, 0xca, 0x1f, 0xd4, 0x79, 0x11, 0xa2, 0x07, 0x66, 0x9a, 0xdf, 0xc5, 0xbe, 0x29,
	0xd2, 0x46, 0x24, 0x22, 0x7c, 0x06, 0x0f, 0xbe, 0x90, 0x8c, 0x2e, 0xbf, 0xdd, 0x2c, 0x78, 0x4c,
	0xfc, 0xa1, 0x3a, 0x04, 0x99, 0x9c, 0xf1, 0x98, 0xe0, 0x09, 0x38, 0x3c, 0x4b, 0x6e, 0x28, 0x5b,
	0x72, 0xdf, 0x3a, 0x35, 0x26, 0x07, 0x91, 0xcd, 0xb3, 0xe4, 0x2d, 0x5b, 0xf2, 0xa9, 0x09, 0x7d,
	0x1a, 0x4f, 0x1d, 0xb0, 0x64, 0x79, 0x78, 0x01, 0x87, 0x6b, 0x3c, 0xf3, 0x94, 0xb3, 0x9c, 0xe0,
	0x18, 0x06, 0x9c, 0xc6, 0x82, 0xa6, 0x19, 0x55, 0x5f, 0x77, 0x20, 0x86, 0xdf, 0x0d, 0x78, 0x74,
	0x95, 0x25, 0xef, 0x78, 0x42, 0xd9, 0x7d, 0x95, 0xa2, 0x6c, 0x58, 0x09, 0x35, 0x2f, 0x7b, 0xb2,
	0x65, 0xad, 0xde, 0xde, 0xa5, 0xde, 0xe9, 0xaa, 0xef, 0x48, 0x3c, 0x17, 0xa3, 0x50, 0xfc, 0xf6,
	0x52, 0x38, 0xd0, 0x15, 0xfe, 0x32, 0x60, 0xa4, 0x4f, 0xd2, 0x07, 0xeb, 0xee, 0xab, 0x20, 0x60,
	0x28, 0x21, 0x2a, 0xfe, 0x7f, 0x33, 0xf6, 0xc1, 0x5e, 0xdc, 0xce, 0x19, 0x23, 0x2b, 0x31, 0x10,
	0x33, 0xaa, 0x43, 0x7c, 0x0a, 0x6e, 0x99, 0x93, 0x4c, 0x4a, 0xb1, 0x85, 0x14, 0xa7, 0x4a, 0x6c,
	0x9d, 0xff, 0x35, 0x3c, 0xec, 0x0e, 0xbf, 0x6c, 0xad, 0x29, 0x69, 0xac, 0x03, 0x5a, 0x3a, 0x20,
	0x7a, 0x30, 0xcc, 0x57, 0xbc, 0xc8, 0x55, 0x27, 0x19, 0x84, 0x3f, 0x0d, 0x38, 0xd0, 0x36, 0xe2,
	0xdf, 0x39, 0x86, 0x92, 0x5f, 0xb3, 0x2b, 0xe5, 0x5f, 0xec, 0xca, 0xba, 0x8b, 0xae, 0xe6, 0x62,
	0xc7, 0xa8, 0x0f, 0x30, 0xea, 0xac, 0xd0, 0x2e, 0x9f, 0x06, 0x7b, 0xf9, 0x14, 0xc1, 0x78, 0x4a,
	0x59, 0xfc, 0xbe, 0x52, 0x5c, 0x5b, 0xa5, 0x80, 0x8d, 0x16, 0xd8, 0xd3, 0x2c, 0x6a, 0x0d, 0x52,
	0xdc, 0xa4, 0x43, 0x51, 0xcd, 0x74, 0xa2, 0x61, 0x4a, 0xb2, 0x5b, 0x11, 0xc2, 0x29, 0x1c, 0x5e,
	0xa7, 0xf1, 0xbc, 0x20, 0x15, 0xc3, 0x8d, 0xf6, 0x7b, 0xea, 0x0a, 0x67, 0x80, 0xeb, 0x18, 0xf7,
	0x32, 0xe7, 0xf9, 0xef, 0x3e, 0xd8, 0x6f, 0xe4, 0x3b, 0x8a, 0xaf, 0xc0, 0x92, 0x1b, 0x89, 0x9e,
	0x7c, 0x53, 0xcf, 0xb4, 0xdf, 0x5e, 0xf0, 0x64, 0x23, 0x2b, 0x3b, 0x86, 0x3d, 0x7c, 0x09, 0x43,
	0x31, 0x21, 0x7c, 0xac, 0x2a, 0xd6, 0x17, 0x30, 0xf0, 0xf4, 0x64, 0x73, 0xeb, 0x1c, 0xdc, 0xc6,
	0x2d, 0x3c, 0x56, 0x45, 0x9b, 0x33, 0x09, 0xb6, 0x1c, 0xd4, 0x00, 0x33, 0x80, 0xd6, 0x00, 0xf4,
	0x55, 0x61, 0xc7, 0xd7, 0xe0, 0x64, 0xcb, 0x49, 0xc3, 0xe2, 0x02, 0xdc, 0xe6, 0x19, 0x6e, 0x58,
	0x6c, 0xfe, 0x81, 0x04, 0x7e, 0xf7, 0xa0, 0x41, 0x78, 0x0d, 0x4e, 0xfd, 0xca, 0xe1, 0x51, 0x5b,
	0xa7, 0x79, 0x70, 0xdc, 0xc9, 0xd7, 0xd7, 0x3f, 0x5a, 0xe2, 0xe4, 0xc5, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x4a, 0x56, 0x14, 0x02, 0xcf, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	Regist(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	BindPhone(ctx context.Context, in *BindPhoneRequest, opts ...grpc.CallOption) (*BindPhoneReponse, error)
	UpdateInfo(ctx context.Context, in *UpdateInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error)
	OrgRegist(ctx context.Context, in *OrgRegistRequest, opts ...grpc.CallOption) (*OrgRegistResponse, error)
	OrgLogin(ctx context.Context, in *OrgLoginRequest, opts ...grpc.CallOption) (*OrgLoginResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Regist(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistResponse, error) {
	out := new(RegistResponse)
	err := c.cc.Invoke(ctx, "/proto.Account/Regist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.Account/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) BindPhone(ctx context.Context, in *BindPhoneRequest, opts ...grpc.CallOption) (*BindPhoneReponse, error) {
	out := new(BindPhoneReponse)
	err := c.cc.Invoke(ctx, "/proto.Account/BindPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateInfo(ctx context.Context, in *UpdateInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error) {
	out := new(UpdateInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.Account/UpdateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) OrgRegist(ctx context.Context, in *OrgRegistRequest, opts ...grpc.CallOption) (*OrgRegistResponse, error) {
	out := new(OrgRegistResponse)
	err := c.cc.Invoke(ctx, "/proto.Account/OrgRegist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) OrgLogin(ctx context.Context, in *OrgLoginRequest, opts ...grpc.CallOption) (*OrgLoginResponse, error) {
	out := new(OrgLoginResponse)
	err := c.cc.Invoke(ctx, "/proto.Account/OrgLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	Regist(context.Context, *RegistRequest) (*RegistResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	BindPhone(context.Context, *BindPhoneRequest) (*BindPhoneReponse, error)
	UpdateInfo(context.Context, *UpdateInfoRequest) (*UpdateInfoResponse, error)
	OrgRegist(context.Context, *OrgRegistRequest) (*OrgRegistResponse, error)
	OrgLogin(context.Context, *OrgLoginRequest) (*OrgLoginResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) Regist(ctx context.Context, req *RegistRequest) (*RegistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Regist not implemented")
}
func (*UnimplementedAccountServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAccountServer) BindPhone(ctx context.Context, req *BindPhoneRequest) (*BindPhoneReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindPhone not implemented")
}
func (*UnimplementedAccountServer) UpdateInfo(ctx context.Context, req *UpdateInfoRequest) (*UpdateInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInfo not implemented")
}
func (*UnimplementedAccountServer) OrgRegist(ctx context.Context, req *OrgRegistRequest) (*OrgRegistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrgRegist not implemented")
}
func (*UnimplementedAccountServer) OrgLogin(ctx context.Context, req *OrgLoginRequest) (*OrgLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrgLogin not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Regist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Regist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/Regist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Regist(ctx, req.(*RegistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_BindPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).BindPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/BindPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).BindPhone(ctx, req.(*BindPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/UpdateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateInfo(ctx, req.(*UpdateInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_OrgRegist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgRegistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).OrgRegist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/OrgRegist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).OrgRegist(ctx, req.(*OrgRegistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_OrgLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).OrgLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/OrgLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).OrgLogin(ctx, req.(*OrgLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Regist",
			Handler:    _Account_Regist_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
		{
			MethodName: "BindPhone",
			Handler:    _Account_BindPhone_Handler,
		},
		{
			MethodName: "UpdateInfo",
			Handler:    _Account_UpdateInfo_Handler,
		},
		{
			MethodName: "OrgRegist",
			Handler:    _Account_OrgRegist_Handler,
		},
		{
			MethodName: "OrgLogin",
			Handler:    _Account_OrgLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
