// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Head struct {
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reverse              string   `protobuf:"bytes,4,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Head) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Head) GetReverse() string {
	if m != nil {
		return m.Reverse
	}
	return ""
}

type Response struct {
	ErrCode              uint32   `protobuf:"varint,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type HeartBeatRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequest.Unmarshal(m, b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(m, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequest.Size(m)
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *HeartBeatRequest) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type HeartBeatResponse struct {
	Replay               string   `protobuf:"bytes,1,opt,name=replay,proto3" json:"replay,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResponse) Reset()         { *m = HeartBeatResponse{} }
func (m *HeartBeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponse) ProtoMessage()    {}
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *HeartBeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponse.Unmarshal(m, b)
}
func (m *HeartBeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartBeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponse.Merge(m, src)
}
func (m *HeartBeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponse.Size(m)
}
func (m *HeartBeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponse proto.InternalMessageInfo

func (m *HeartBeatResponse) GetReplay() string {
	if m != nil {
		return m.Replay
	}
	return ""
}

func (m *HeartBeatResponse) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func init() {
	proto.RegisterType((*Head)(nil), "proto.Head")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*HeartBeatRequest)(nil), "proto.HeartBeatRequest")
	proto.RegisterType((*HeartBeatResponse)(nil), "proto.HeartBeatResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x89, 0x1b, 0x57, 0x33, 0x28, 0x9c, 0x29, 0x8e, 0x14, 0x16, 0x21, 0x55, 0x2a, 0x1b,
	0x1b, 0x0b, 0x6d, 0x94, 0x83, 0x6b, 0x04, 0x99, 0x7f, 0x10, 0xbd, 0x51, 0x04, 0x73, 0xc9, 0x4d,
	0xa2, 0xe0, 0xbf, 0x97, 0x0d, 0x59, 0x3c, 0xd8, 0x6a, 0xde, 0x37, 0xcc, 0x9b, 0x79, 0x0c, 0x5c,
	0xbc, 0xa5, 0x18, 0xd3, 0xfe, 0x26, 0x73, 0xaa, 0x49, 0x9f, 0xb6, 0xe2, 0x5e, 0x40, 0x6e, 0x29,
	0xec, 0xf4, 0x0a, 0x86, 0x42, 0x07, 0x73, 0x62, 0x85, 0x97, 0x38, 0x49, 0x7d, 0x0d, 0xaa, 0x7e,
	0x46, 0x2a, 0x35, 0xc4, 0x6c, 0x06, 0x2b, 0xfc, 0x80, 0xff, 0x0d, 0x6d, 0xe0, 0x8c, 0xe9, 0x87,
	0xb8, 0x90, 0x91, 0x56, 0x78, 0x85, 0x33, 0xba, 0x7b, 0x38, 0x47, 0x2a, 0x39, 0xed, 0x0b, 0x4d,
	0x53, 0x1b, 0xe6, 0xa7, 0xb4, 0x23, 0x23, 0xac, 0xf0, 0x97, 0x38, 0xa3, 0x5e, 0xc3, 0xb8, 0x61,
	0x7e, 0x2e, 0x1f, 0xed, 0xa4, 0xc2, 0x4e, 0xee, 0x0e, 0x56, 0x5b, 0x0a, 0x5c, 0x1f, 0x29, 0x54,
	0xa4, 0xc3, 0x37, 0x95, 0xaa, 0x35, 0xc8, 0x77, 0x4e, 0xb1, 0xad, 0x50, 0xd8, 0xf4, 0x32, 0xaf,
	0x7b, 0x80, 0xab, 0x23, 0x67, 0x0f, 0xb0, 0x86, 0x91, 0x29, 0x7f, 0x85, 0xdf, 0x6e, 0xee, 0xb4,
	0xb4, 0xbf, 0x8e, 0xed, 0x1f, 0xb7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xba, 0xaf, 0x4e, 0xd6,
	0x26, 0x01, 0x00, 0x00,
}
