// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

///请求更新网络数据
type FetchDataRequest struct {
	Symbols              []string `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Start                string   `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchDataRequest) Reset()         { *m = FetchDataRequest{} }
func (m *FetchDataRequest) String() string { return proto.CompactTextString(m) }
func (*FetchDataRequest) ProtoMessage()    {}
func (*FetchDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *FetchDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchDataRequest.Unmarshal(m, b)
}
func (m *FetchDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchDataRequest.Marshal(b, m, deterministic)
}
func (m *FetchDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchDataRequest.Merge(m, src)
}
func (m *FetchDataRequest) XXX_Size() int {
	return xxx_messageInfo_FetchDataRequest.Size(m)
}
func (m *FetchDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchDataRequest proto.InternalMessageInfo

func (m *FetchDataRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

func (m *FetchDataRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *FetchDataRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type FetchDataReponse struct {
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchDataReponse) Reset()         { *m = FetchDataReponse{} }
func (m *FetchDataReponse) String() string { return proto.CompactTextString(m) }
func (*FetchDataReponse) ProtoMessage()    {}
func (*FetchDataReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *FetchDataReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchDataReponse.Unmarshal(m, b)
}
func (m *FetchDataReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchDataReponse.Marshal(b, m, deterministic)
}
func (m *FetchDataReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchDataReponse.Merge(m, src)
}
func (m *FetchDataReponse) XXX_Size() int {
	return xxx_messageInfo_FetchDataReponse.Size(m)
}
func (m *FetchDataReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchDataReponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchDataReponse proto.InternalMessageInfo

func (m *FetchDataReponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type LoadDataRequest struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Start                string   `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	BarType              string   `protobuf:"bytes,5,opt,name=bar_type,json=barType,proto3" json:"bar_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadDataRequest) Reset()         { *m = LoadDataRequest{} }
func (m *LoadDataRequest) String() string { return proto.CompactTextString(m) }
func (*LoadDataRequest) ProtoMessage()    {}
func (*LoadDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *LoadDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadDataRequest.Unmarshal(m, b)
}
func (m *LoadDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadDataRequest.Marshal(b, m, deterministic)
}
func (m *LoadDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadDataRequest.Merge(m, src)
}
func (m *LoadDataRequest) XXX_Size() int {
	return xxx_messageInfo_LoadDataRequest.Size(m)
}
func (m *LoadDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadDataRequest proto.InternalMessageInfo

func (m *LoadDataRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *LoadDataRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *LoadDataRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *LoadDataRequest) GetBarType() string {
	if m != nil {
		return m.BarType
	}
	return ""
}

type LoadDataReponse struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	JsDF                 []byte   `protobuf:"bytes,3,opt,name=jsDF,proto3" json:"jsDF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadDataReponse) Reset()         { *m = LoadDataReponse{} }
func (m *LoadDataReponse) String() string { return proto.CompactTextString(m) }
func (*LoadDataReponse) ProtoMessage()    {}
func (*LoadDataReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *LoadDataReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadDataReponse.Unmarshal(m, b)
}
func (m *LoadDataReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadDataReponse.Marshal(b, m, deterministic)
}
func (m *LoadDataReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadDataReponse.Merge(m, src)
}
func (m *LoadDataReponse) XXX_Size() int {
	return xxx_messageInfo_LoadDataReponse.Size(m)
}
func (m *LoadDataReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadDataReponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadDataReponse proto.InternalMessageInfo

func (m *LoadDataReponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *LoadDataReponse) GetJsDF() []byte {
	if m != nil {
		return m.JsDF
	}
	return nil
}

type PredictSymbolRequest struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictSymbolRequest) Reset()         { *m = PredictSymbolRequest{} }
func (m *PredictSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*PredictSymbolRequest) ProtoMessage()    {}
func (*PredictSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *PredictSymbolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictSymbolRequest.Unmarshal(m, b)
}
func (m *PredictSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictSymbolRequest.Marshal(b, m, deterministic)
}
func (m *PredictSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictSymbolRequest.Merge(m, src)
}
func (m *PredictSymbolRequest) XXX_Size() int {
	return xxx_messageInfo_PredictSymbolRequest.Size(m)
}
func (m *PredictSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictSymbolRequest proto.InternalMessageInfo

func (m *PredictSymbolRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type PredictSymbolResponse struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastOhlc             []string `protobuf:"bytes,3,rep,name=last_ohlc,json=lastOhlc,proto3" json:"last_ohlc,omitempty"`
	PredictOhlc          string   `protobuf:"bytes,4,opt,name=predict_ohlc,json=predictOhlc,proto3" json:"predict_ohlc,omitempty"`
	Ptime                string   `protobuf:"bytes,5,opt,name=ptime,proto3" json:"ptime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictSymbolResponse) Reset()         { *m = PredictSymbolResponse{} }
func (m *PredictSymbolResponse) String() string { return proto.CompactTextString(m) }
func (*PredictSymbolResponse) ProtoMessage()    {}
func (*PredictSymbolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *PredictSymbolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictSymbolResponse.Unmarshal(m, b)
}
func (m *PredictSymbolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictSymbolResponse.Marshal(b, m, deterministic)
}
func (m *PredictSymbolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictSymbolResponse.Merge(m, src)
}
func (m *PredictSymbolResponse) XXX_Size() int {
	return xxx_messageInfo_PredictSymbolResponse.Size(m)
}
func (m *PredictSymbolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictSymbolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictSymbolResponse proto.InternalMessageInfo

func (m *PredictSymbolResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *PredictSymbolResponse) GetLastOhlc() []string {
	if m != nil {
		return m.LastOhlc
	}
	return nil
}

func (m *PredictSymbolResponse) GetPredictOhlc() string {
	if m != nil {
		return m.PredictOhlc
	}
	return ""
}

func (m *PredictSymbolResponse) GetPtime() string {
	if m != nil {
		return m.Ptime
	}
	return ""
}

type TimerTaskRequest struct {
	Taskid               int32    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Ext                  string   `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimerTaskRequest) Reset()         { *m = TimerTaskRequest{} }
func (m *TimerTaskRequest) String() string { return proto.CompactTextString(m) }
func (*TimerTaskRequest) ProtoMessage()    {}
func (*TimerTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *TimerTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerTaskRequest.Unmarshal(m, b)
}
func (m *TimerTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerTaskRequest.Marshal(b, m, deterministic)
}
func (m *TimerTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerTaskRequest.Merge(m, src)
}
func (m *TimerTaskRequest) XXX_Size() int {
	return xxx_messageInfo_TimerTaskRequest.Size(m)
}
func (m *TimerTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimerTaskRequest proto.InternalMessageInfo

func (m *TimerTaskRequest) GetTaskid() int32 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *TimerTaskRequest) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

type TimerTaskResponse struct {
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimerTaskResponse) Reset()         { *m = TimerTaskResponse{} }
func (m *TimerTaskResponse) String() string { return proto.CompactTextString(m) }
func (*TimerTaskResponse) ProtoMessage()    {}
func (*TimerTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *TimerTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerTaskResponse.Unmarshal(m, b)
}
func (m *TimerTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerTaskResponse.Marshal(b, m, deterministic)
}
func (m *TimerTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerTaskResponse.Merge(m, src)
}
func (m *TimerTaskResponse) XXX_Size() int {
	return xxx_messageInfo_TimerTaskResponse.Size(m)
}
func (m *TimerTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimerTaskResponse proto.InternalMessageInfo

func (m *TimerTaskResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TimerTaskResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetSymbolOhlcRequest struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSymbolOhlcRequest) Reset()         { *m = GetSymbolOhlcRequest{} }
func (m *GetSymbolOhlcRequest) String() string { return proto.CompactTextString(m) }
func (*GetSymbolOhlcRequest) ProtoMessage()    {}
func (*GetSymbolOhlcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *GetSymbolOhlcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSymbolOhlcRequest.Unmarshal(m, b)
}
func (m *GetSymbolOhlcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSymbolOhlcRequest.Marshal(b, m, deterministic)
}
func (m *GetSymbolOhlcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSymbolOhlcRequest.Merge(m, src)
}
func (m *GetSymbolOhlcRequest) XXX_Size() int {
	return xxx_messageInfo_GetSymbolOhlcRequest.Size(m)
}
func (m *GetSymbolOhlcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSymbolOhlcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSymbolOhlcRequest proto.InternalMessageInfo

func (m *GetSymbolOhlcRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetSymbolOhlcRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type GetSymbolOhlcResponse struct {
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ohlc                 string   `protobuf:"bytes,3,opt,name=ohlc,proto3" json:"ohlc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSymbolOhlcResponse) Reset()         { *m = GetSymbolOhlcResponse{} }
func (m *GetSymbolOhlcResponse) String() string { return proto.CompactTextString(m) }
func (*GetSymbolOhlcResponse) ProtoMessage()    {}
func (*GetSymbolOhlcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{9}
}

func (m *GetSymbolOhlcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSymbolOhlcResponse.Unmarshal(m, b)
}
func (m *GetSymbolOhlcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSymbolOhlcResponse.Marshal(b, m, deterministic)
}
func (m *GetSymbolOhlcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSymbolOhlcResponse.Merge(m, src)
}
func (m *GetSymbolOhlcResponse) XXX_Size() int {
	return xxx_messageInfo_GetSymbolOhlcResponse.Size(m)
}
func (m *GetSymbolOhlcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSymbolOhlcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSymbolOhlcResponse proto.InternalMessageInfo

func (m *GetSymbolOhlcResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetSymbolOhlcResponse) GetOhlc() string {
	if m != nil {
		return m.Ohlc
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchDataRequest)(nil), "proto.FetchDataRequest")
	proto.RegisterType((*FetchDataReponse)(nil), "proto.FetchDataReponse")
	proto.RegisterType((*LoadDataRequest)(nil), "proto.LoadDataRequest")
	proto.RegisterType((*LoadDataReponse)(nil), "proto.LoadDataReponse")
	proto.RegisterType((*PredictSymbolRequest)(nil), "proto.PredictSymbolRequest")
	proto.RegisterType((*PredictSymbolResponse)(nil), "proto.PredictSymbolResponse")
	proto.RegisterType((*TimerTaskRequest)(nil), "proto.TimerTaskRequest")
	proto.RegisterType((*TimerTaskResponse)(nil), "proto.TimerTaskResponse")
	proto.RegisterType((*GetSymbolOhlcRequest)(nil), "proto.GetSymbolOhlcRequest")
	proto.RegisterType((*GetSymbolOhlcResponse)(nil), "proto.GetSymbolOhlcResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x8f, 0x93, 0x40,
	0x14, 0x5f, 0x0a, 0xec, 0x96, 0xe7, 0x6e, 0xac, 0x13, 0x76, 0x1d, 0x59, 0x0f, 0x75, 0x0e, 0x86,
	0x53, 0x63, 0xf4, 0x64, 0xb2, 0x46, 0xa3, 0x9b, 0xf5, 0xd2, 0xc4, 0x06, 0xb9, 0x37, 0x03, 0x4c,
	0x5a, 0x2c, 0x14, 0x64, 0xc6, 0xc4, 0x7e, 0x00, 0x3f, 0xab, 0x5f, 0xc3, 0x30, 0x33, 0x10, 0x4a,
	0xa9, 0xdd, 0x13, 0xef, 0xef, 0xef, 0xf7, 0xe6, 0xbd, 0x1f, 0x00, 0x09, 0x15, 0x74, 0x56, 0x56,
	0x85, 0x28, 0x90, 0x2d, 0x3f, 0x24, 0x84, 0xc9, 0x03, 0x13, 0xf1, 0xfa, 0x9e, 0x0a, 0x1a, 0xb0,
	0x9f, 0xbf, 0x18, 0x17, 0x08, 0xc3, 0x05, 0xdf, 0xe5, 0x51, 0x91, 0x71, 0x3c, 0x9a, 0x9a, 0xbe,
	0x13, 0x34, 0x2e, 0x72, 0xc1, 0xe6, 0x82, 0x56, 0x02, 0x9b, 0x53, 0xc3, 0x77, 0x02, 0xe5, 0xa0,
	0x09, 0x98, 0x6c, 0x9b, 0x60, 0x4b, 0xc6, 0x6a, 0x93, 0xbc, 0xde, 0x43, 0x2d, 0x8b, 0x2d, 0x67,
	0x08, 0x81, 0x15, 0x17, 0x09, 0xc3, 0xa3, 0xa9, 0xe1, 0xdb, 0x81, 0xb4, 0x49, 0x06, 0x4f, 0xe7,
	0x05, 0x4d, 0xba, 0xe4, 0x37, 0x70, 0xae, 0xd8, 0x64, 0xa1, 0x13, 0x68, 0xef, 0xb1, 0xd4, 0xe8,
	0x05, 0x8c, 0x23, 0x5a, 0x2d, 0xc5, 0xae, 0x64, 0xd8, 0x96, 0xe1, 0x8b, 0x88, 0x56, 0xe1, 0xae,
	0x64, 0xe4, 0x43, 0x97, 0x4d, 0x0d, 0x75, 0x8c, 0x0d, 0x81, 0xf5, 0x83, 0xdf, 0x3f, 0x48, 0xb2,
	0xcb, 0x40, 0xda, 0x64, 0x06, 0xee, 0xa2, 0x62, 0x49, 0x1a, 0x8b, 0xef, 0xb2, 0xe8, 0xc4, 0xc4,
	0xe4, 0x8f, 0x01, 0xd7, 0xbd, 0x06, 0xfe, 0x7f, 0xd6, 0x5b, 0x70, 0x32, 0xca, 0xc5, 0xb2, 0x58,
	0x67, 0x31, 0x36, 0xe5, 0xea, 0xc7, 0x75, 0xe0, 0xdb, 0x3a, 0x8b, 0xd1, 0x2b, 0xb8, 0x2c, 0x15,
	0x9a, 0xca, 0xab, 0x37, 0x3f, 0xd1, 0x31, 0x59, 0xe2, 0x82, 0x5d, 0x8a, 0x34, 0x6f, 0x1e, 0xae,
	0x1c, 0x72, 0x07, 0x93, 0x30, 0xcd, 0x59, 0x15, 0x52, 0xbe, 0xe9, 0xcc, 0x2c, 0x28, 0xdf, 0xa4,
	0x89, 0x3e, 0x87, 0xf6, 0xe4, 0x3e, 0x7f, 0x37, 0x3b, 0xae, 0x4d, 0xf2, 0x1e, 0x9e, 0x75, 0xba,
	0xf9, 0xd1, 0x5b, 0xd6, 0xad, 0x39, 0x5f, 0x35, 0xad, 0x39, 0x5f, 0x91, 0xcf, 0xe0, 0x7e, 0x65,
	0xfa, 0xed, 0xf5, 0x7c, 0xa7, 0x4e, 0x8c, 0xc0, 0x4a, 0xa8, 0x60, 0x1a, 0x42, 0xda, 0xe4, 0x0b,
	0x5c, 0xf7, 0x30, 0xf8, 0xc9, 0xcb, 0xe9, 0xf5, 0x49, 0x90, 0xda, 0x7e, 0xfb, 0x77, 0x04, 0x56,
	0x7d, 0x75, 0xf4, 0x11, 0x9c, 0x56, 0x97, 0xe8, 0xb9, 0xfa, 0x13, 0x66, 0x7d, 0xfd, 0x7b, 0x03,
	0x09, 0xc9, 0x49, 0xce, 0xd0, 0x1d, 0x8c, 0x1b, 0x09, 0xa1, 0x1b, 0x5d, 0xd6, 0x53, 0xb0, 0x77,
	0x18, 0x6f, 0xba, 0x3f, 0x81, 0xd3, 0xee, 0xb2, 0xa5, 0xef, 0xdf, 0xc6, 0xc3, 0x87, 0x09, 0xde,
	0x20, 0xcc, 0xe1, 0x6a, 0x6f, 0x1d, 0xe8, 0x56, 0x17, 0x0f, 0x2d, 0xda, 0x7b, 0x39, 0x9c, 0x6c,
	0xd1, 0x16, 0x70, 0xb5, 0x27, 0xd0, 0x16, 0x6d, 0x48, 0xe7, 0x2d, 0xda, 0xa0, 0xa6, 0xc9, 0x99,
	0x6f, 0xbc, 0x31, 0xa2, 0x73, 0x59, 0xf2, 0xee, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x88,
	0x3e, 0xc1, 0x6a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	FetchData(ctx context.Context, in *FetchDataRequest, opts ...grpc.CallOption) (*FetchDataReponse, error)
	LoadData(ctx context.Context, in *LoadDataRequest, opts ...grpc.CallOption) (*LoadDataReponse, error)
	TimerTask(ctx context.Context, in *TimerTaskRequest, opts ...grpc.CallOption) (*TimerTaskResponse, error)
	GetSymbolOhlc(ctx context.Context, in *GetSymbolOhlcRequest, opts ...grpc.CallOption) (*GetSymbolOhlcResponse, error)
	PredictSymbol(ctx context.Context, opts ...grpc.CallOption) (Data_PredictSymbolClient, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) FetchData(ctx context.Context, in *FetchDataRequest, opts ...grpc.CallOption) (*FetchDataReponse, error) {
	out := new(FetchDataReponse)
	err := c.cc.Invoke(ctx, "/proto.Data/FetchData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) LoadData(ctx context.Context, in *LoadDataRequest, opts ...grpc.CallOption) (*LoadDataReponse, error) {
	out := new(LoadDataReponse)
	err := c.cc.Invoke(ctx, "/proto.Data/LoadData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) TimerTask(ctx context.Context, in *TimerTaskRequest, opts ...grpc.CallOption) (*TimerTaskResponse, error) {
	out := new(TimerTaskResponse)
	err := c.cc.Invoke(ctx, "/proto.Data/TimerTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetSymbolOhlc(ctx context.Context, in *GetSymbolOhlcRequest, opts ...grpc.CallOption) (*GetSymbolOhlcResponse, error) {
	out := new(GetSymbolOhlcResponse)
	err := c.cc.Invoke(ctx, "/proto.Data/GetSymbolOhlc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) PredictSymbol(ctx context.Context, opts ...grpc.CallOption) (Data_PredictSymbolClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[0], "/proto.Data/PredictSymbol", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataPredictSymbolClient{stream}
	return x, nil
}

type Data_PredictSymbolClient interface {
	Send(*PredictSymbolRequest) error
	Recv() (*PredictSymbolResponse, error)
	grpc.ClientStream
}

type dataPredictSymbolClient struct {
	grpc.ClientStream
}

func (x *dataPredictSymbolClient) Send(m *PredictSymbolRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataPredictSymbolClient) Recv() (*PredictSymbolResponse, error) {
	m := new(PredictSymbolResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	FetchData(context.Context, *FetchDataRequest) (*FetchDataReponse, error)
	LoadData(context.Context, *LoadDataRequest) (*LoadDataReponse, error)
	TimerTask(context.Context, *TimerTaskRequest) (*TimerTaskResponse, error)
	GetSymbolOhlc(context.Context, *GetSymbolOhlcRequest) (*GetSymbolOhlcResponse, error)
	PredictSymbol(Data_PredictSymbolServer) error
}

// UnimplementedDataServer can be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (*UnimplementedDataServer) FetchData(ctx context.Context, req *FetchDataRequest) (*FetchDataReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchData not implemented")
}
func (*UnimplementedDataServer) LoadData(ctx context.Context, req *LoadDataRequest) (*LoadDataReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadData not implemented")
}
func (*UnimplementedDataServer) TimerTask(ctx context.Context, req *TimerTaskRequest) (*TimerTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimerTask not implemented")
}
func (*UnimplementedDataServer) GetSymbolOhlc(ctx context.Context, req *GetSymbolOhlcRequest) (*GetSymbolOhlcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbolOhlc not implemented")
}
func (*UnimplementedDataServer) PredictSymbol(srv Data_PredictSymbolServer) error {
	return status.Errorf(codes.Unimplemented, "method PredictSymbol not implemented")
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_FetchData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).FetchData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Data/FetchData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).FetchData(ctx, req.(*FetchDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_LoadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).LoadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Data/LoadData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).LoadData(ctx, req.(*LoadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_TimerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimerTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).TimerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Data/TimerTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).TimerTask(ctx, req.(*TimerTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_GetSymbolOhlc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolOhlcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetSymbolOhlc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Data/GetSymbolOhlc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetSymbolOhlc(ctx, req.(*GetSymbolOhlcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_PredictSymbol_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).PredictSymbol(&dataPredictSymbolServer{stream})
}

type Data_PredictSymbolServer interface {
	Send(*PredictSymbolResponse) error
	Recv() (*PredictSymbolRequest, error)
	grpc.ServerStream
}

type dataPredictSymbolServer struct {
	grpc.ServerStream
}

func (x *dataPredictSymbolServer) Send(m *PredictSymbolResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataPredictSymbolServer) Recv() (*PredictSymbolRequest, error) {
	m := new(PredictSymbolRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchData",
			Handler:    _Data_FetchData_Handler,
		},
		{
			MethodName: "LoadData",
			Handler:    _Data_LoadData_Handler,
		},
		{
			MethodName: "TimerTask",
			Handler:    _Data_TimerTask_Handler,
		},
		{
			MethodName: "GetSymbolOhlc",
			Handler:    _Data_GetSymbolOhlc_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PredictSymbol",
			Handler:       _Data_PredictSymbol_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "data.proto",
}
