// Code generated by protoc-gen-go. DO NOT EDIT.
// source: market.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyActionRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Uin                  uint64   `protobuf:"varint,3,opt,name=uin,proto3" json:"uin,omitempty"`
	Act                  string   `protobuf:"bytes,4,opt,name=act,proto3" json:"act,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyActionRequest) Reset()         { *m = NotifyActionRequest{} }
func (m *NotifyActionRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyActionRequest) ProtoMessage()    {}
func (*NotifyActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{0}
}

func (m *NotifyActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyActionRequest.Unmarshal(m, b)
}
func (m *NotifyActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyActionRequest.Marshal(b, m, deterministic)
}
func (m *NotifyActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyActionRequest.Merge(m, src)
}
func (m *NotifyActionRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyActionRequest.Size(m)
}
func (m *NotifyActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyActionRequest proto.InternalMessageInfo

func (m *NotifyActionRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *NotifyActionRequest) GetUin() uint64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *NotifyActionRequest) GetAct() string {
	if m != nil {
		return m.Act
	}
	return ""
}

type NotifyActionResponse struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyActionResponse) Reset()         { *m = NotifyActionResponse{} }
func (m *NotifyActionResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyActionResponse) ProtoMessage()    {}
func (*NotifyActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{1}
}

func (m *NotifyActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyActionResponse.Unmarshal(m, b)
}
func (m *NotifyActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyActionResponse.Marshal(b, m, deterministic)
}
func (m *NotifyActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyActionResponse.Merge(m, src)
}
func (m *NotifyActionResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyActionResponse.Size(m)
}
func (m *NotifyActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyActionResponse proto.InternalMessageInfo

func (m *NotifyActionResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PaySlotRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Sid                  uint32   `protobuf:"varint,3,opt,name=sid,proto3" json:"sid,omitempty"`
	Months               int32    `protobuf:"varint,4,opt,name=months,proto3" json:"months,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaySlotRequest) Reset()         { *m = PaySlotRequest{} }
func (m *PaySlotRequest) String() string { return proto.CompactTextString(m) }
func (*PaySlotRequest) ProtoMessage()    {}
func (*PaySlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{2}
}

func (m *PaySlotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaySlotRequest.Unmarshal(m, b)
}
func (m *PaySlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaySlotRequest.Marshal(b, m, deterministic)
}
func (m *PaySlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaySlotRequest.Merge(m, src)
}
func (m *PaySlotRequest) XXX_Size() int {
	return xxx_messageInfo_PaySlotRequest.Size(m)
}
func (m *PaySlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaySlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaySlotRequest proto.InternalMessageInfo

func (m *PaySlotRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PaySlotRequest) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *PaySlotRequest) GetMonths() int32 {
	if m != nil {
		return m.Months
	}
	return 0
}

type PaySlotResponse struct {
	Myslots              []byte   `protobuf:"bytes,3,opt,name=myslots,proto3" json:"myslots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaySlotResponse) Reset()         { *m = PaySlotResponse{} }
func (m *PaySlotResponse) String() string { return proto.CompactTextString(m) }
func (*PaySlotResponse) ProtoMessage()    {}
func (*PaySlotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{3}
}

func (m *PaySlotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaySlotResponse.Unmarshal(m, b)
}
func (m *PaySlotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaySlotResponse.Marshal(b, m, deterministic)
}
func (m *PaySlotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaySlotResponse.Merge(m, src)
}
func (m *PaySlotResponse) XXX_Size() int {
	return xxx_messageInfo_PaySlotResponse.Size(m)
}
func (m *PaySlotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaySlotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaySlotResponse proto.InternalMessageInfo

func (m *PaySlotResponse) GetMyslots() []byte {
	if m != nil {
		return m.Myslots
	}
	return nil
}

type ListUsrShareRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Start                string   `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsrShareRequest) Reset()         { *m = ListUsrShareRequest{} }
func (m *ListUsrShareRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsrShareRequest) ProtoMessage()    {}
func (*ListUsrShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{4}
}

func (m *ListUsrShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsrShareRequest.Unmarshal(m, b)
}
func (m *ListUsrShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsrShareRequest.Marshal(b, m, deterministic)
}
func (m *ListUsrShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsrShareRequest.Merge(m, src)
}
func (m *ListUsrShareRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsrShareRequest.Size(m)
}
func (m *ListUsrShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsrShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsrShareRequest proto.InternalMessageInfo

func (m *ListUsrShareRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListUsrShareRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ListUsrShareRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type ListUsrShareResponse struct {
	Shares               []byte   `protobuf:"bytes,3,opt,name=shares,proto3" json:"shares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsrShareResponse) Reset()         { *m = ListUsrShareResponse{} }
func (m *ListUsrShareResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsrShareResponse) ProtoMessage()    {}
func (*ListUsrShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{5}
}

func (m *ListUsrShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsrShareResponse.Unmarshal(m, b)
}
func (m *ListUsrShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsrShareResponse.Marshal(b, m, deterministic)
}
func (m *ListUsrShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsrShareResponse.Merge(m, src)
}
func (m *ListUsrShareResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsrShareResponse.Size(m)
}
func (m *ListUsrShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsrShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsrShareResponse proto.InternalMessageInfo

func (m *ListUsrShareResponse) GetShares() []byte {
	if m != nil {
		return m.Shares
	}
	return nil
}

type ListOrgShareRequest struct {
	Oid                  uint64   `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Start                string   `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrgShareRequest) Reset()         { *m = ListOrgShareRequest{} }
func (m *ListOrgShareRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrgShareRequest) ProtoMessage()    {}
func (*ListOrgShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{6}
}

func (m *ListOrgShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrgShareRequest.Unmarshal(m, b)
}
func (m *ListOrgShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrgShareRequest.Marshal(b, m, deterministic)
}
func (m *ListOrgShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrgShareRequest.Merge(m, src)
}
func (m *ListOrgShareRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrgShareRequest.Size(m)
}
func (m *ListOrgShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrgShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrgShareRequest proto.InternalMessageInfo

func (m *ListOrgShareRequest) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *ListOrgShareRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ListOrgShareRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type ListOrgShareResponse struct {
	Shares               []byte   `protobuf:"bytes,3,opt,name=shares,proto3" json:"shares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrgShareResponse) Reset()         { *m = ListOrgShareResponse{} }
func (m *ListOrgShareResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrgShareResponse) ProtoMessage()    {}
func (*ListOrgShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{7}
}

func (m *ListOrgShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrgShareResponse.Unmarshal(m, b)
}
func (m *ListOrgShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrgShareResponse.Marshal(b, m, deterministic)
}
func (m *ListOrgShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrgShareResponse.Merge(m, src)
}
func (m *ListOrgShareResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrgShareResponse.Size(m)
}
func (m *ListOrgShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrgShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrgShareResponse proto.InternalMessageInfo

func (m *ListOrgShareResponse) GetShares() []byte {
	if m != nil {
		return m.Shares
	}
	return nil
}

type PayOrgRequest struct {
	Op                   uint64   `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Checker              uint64   `protobuf:"varint,3,opt,name=checker,proto3" json:"checker,omitempty"`
	Oid                  uint64   `protobuf:"varint,4,opt,name=oid,proto3" json:"oid,omitempty"`
	Paylist              []byte   `protobuf:"bytes,5,opt,name=paylist,proto3" json:"paylist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrgRequest) Reset()         { *m = PayOrgRequest{} }
func (m *PayOrgRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrgRequest) ProtoMessage()    {}
func (*PayOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{8}
}

func (m *PayOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrgRequest.Unmarshal(m, b)
}
func (m *PayOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrgRequest.Marshal(b, m, deterministic)
}
func (m *PayOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrgRequest.Merge(m, src)
}
func (m *PayOrgRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrgRequest.Size(m)
}
func (m *PayOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrgRequest proto.InternalMessageInfo

func (m *PayOrgRequest) GetOp() uint64 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *PayOrgRequest) GetChecker() uint64 {
	if m != nil {
		return m.Checker
	}
	return 0
}

func (m *PayOrgRequest) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *PayOrgRequest) GetPaylist() []byte {
	if m != nil {
		return m.Paylist
	}
	return nil
}

type PayOrgResponse struct {
	Op                   uint64   `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Checker              uint64   `protobuf:"varint,3,opt,name=checker,proto3" json:"checker,omitempty"`
	Oid                  uint64   `protobuf:"varint,4,opt,name=oid,proto3" json:"oid,omitempty"`
	Billno               string   `protobuf:"bytes,5,opt,name=billno,proto3" json:"billno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrgResponse) Reset()         { *m = PayOrgResponse{} }
func (m *PayOrgResponse) String() string { return proto.CompactTextString(m) }
func (*PayOrgResponse) ProtoMessage()    {}
func (*PayOrgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{9}
}

func (m *PayOrgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrgResponse.Unmarshal(m, b)
}
func (m *PayOrgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrgResponse.Marshal(b, m, deterministic)
}
func (m *PayOrgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrgResponse.Merge(m, src)
}
func (m *PayOrgResponse) XXX_Size() int {
	return xxx_messageInfo_PayOrgResponse.Size(m)
}
func (m *PayOrgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrgResponse proto.InternalMessageInfo

func (m *PayOrgResponse) GetOp() uint64 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *PayOrgResponse) GetChecker() uint64 {
	if m != nil {
		return m.Checker
	}
	return 0
}

func (m *PayOrgResponse) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *PayOrgResponse) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

///用户预定纪录,供客服跟踪，无需返回
type PreBillRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Months               uint32   `protobuf:"varint,3,opt,name=months,proto3" json:"months,omitempty"`
	Slots                uint32   `protobuf:"varint,4,opt,name=slots,proto3" json:"slots,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	PreTime              string   `protobuf:"bytes,6,opt,name=pre_time,json=preTime,proto3" json:"pre_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreBillRequest) Reset()         { *m = PreBillRequest{} }
func (m *PreBillRequest) String() string { return proto.CompactTextString(m) }
func (*PreBillRequest) ProtoMessage()    {}
func (*PreBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{10}
}

func (m *PreBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreBillRequest.Unmarshal(m, b)
}
func (m *PreBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreBillRequest.Marshal(b, m, deterministic)
}
func (m *PreBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreBillRequest.Merge(m, src)
}
func (m *PreBillRequest) XXX_Size() int {
	return xxx_messageInfo_PreBillRequest.Size(m)
}
func (m *PreBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreBillRequest proto.InternalMessageInfo

func (m *PreBillRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreBillRequest) GetMonths() uint32 {
	if m != nil {
		return m.Months
	}
	return 0
}

func (m *PreBillRequest) GetSlots() uint32 {
	if m != nil {
		return m.Slots
	}
	return 0
}

func (m *PreBillRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PreBillRequest) GetPreTime() string {
	if m != nil {
		return m.PreTime
	}
	return ""
}

type PreBillResponse struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Months               uint32   `protobuf:"varint,3,opt,name=months,proto3" json:"months,omitempty"`
	Slots                uint32   `protobuf:"varint,4,opt,name=slots,proto3" json:"slots,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	PreTime              string   `protobuf:"bytes,6,opt,name=pre_time,json=preTime,proto3" json:"pre_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreBillResponse) Reset()         { *m = PreBillResponse{} }
func (m *PreBillResponse) String() string { return proto.CompactTextString(m) }
func (*PreBillResponse) ProtoMessage()    {}
func (*PreBillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{11}
}

func (m *PreBillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreBillResponse.Unmarshal(m, b)
}
func (m *PreBillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreBillResponse.Marshal(b, m, deterministic)
}
func (m *PreBillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreBillResponse.Merge(m, src)
}
func (m *PreBillResponse) XXX_Size() int {
	return xxx_messageInfo_PreBillResponse.Size(m)
}
func (m *PreBillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PreBillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PreBillResponse proto.InternalMessageInfo

func (m *PreBillResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreBillResponse) GetMonths() uint32 {
	if m != nil {
		return m.Months
	}
	return 0
}

func (m *PreBillResponse) GetSlots() uint32 {
	if m != nil {
		return m.Slots
	}
	return 0
}

func (m *PreBillResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PreBillResponse) GetPreTime() string {
	if m != nil {
		return m.PreTime
	}
	return ""
}

func init() {
	proto.RegisterType((*NotifyActionRequest)(nil), "proto.NotifyActionRequest")
	proto.RegisterType((*NotifyActionResponse)(nil), "proto.NotifyActionResponse")
	proto.RegisterType((*PaySlotRequest)(nil), "proto.PaySlotRequest")
	proto.RegisterType((*PaySlotResponse)(nil), "proto.PaySlotResponse")
	proto.RegisterType((*ListUsrShareRequest)(nil), "proto.ListUsrShareRequest")
	proto.RegisterType((*ListUsrShareResponse)(nil), "proto.ListUsrShareResponse")
	proto.RegisterType((*ListOrgShareRequest)(nil), "proto.ListOrgShareRequest")
	proto.RegisterType((*ListOrgShareResponse)(nil), "proto.ListOrgShareResponse")
	proto.RegisterType((*PayOrgRequest)(nil), "proto.PayOrgRequest")
	proto.RegisterType((*PayOrgResponse)(nil), "proto.PayOrgResponse")
	proto.RegisterType((*PreBillRequest)(nil), "proto.PreBillRequest")
	proto.RegisterType((*PreBillResponse)(nil), "proto.PreBillResponse")
}

func init() { proto.RegisterFile("market.proto", fileDescriptor_3f90997f23a2c3f8) }

var fileDescriptor_3f90997f23a2c3f8 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x6d, 0xbe, 0x36, 0x64, 0x94, 0xa6, 0xc8, 0x4d, 0xa3, 0x25, 0x5c, 0x2a, 0x9f, 0x22, 0x21,
	0xe5, 0x00, 0x07, 0x24, 0x6e, 0x70, 0xab, 0x28, 0x24, 0x72, 0xe1, 0x8c, 0xb6, 0x59, 0x93, 0x58,
	0xdd, 0xb5, 0x17, 0xdb, 0x3d, 0xec, 0x11, 0x7e, 0x06, 0xbf, 0x16, 0xf9, 0x6b, 0xdd, 0x5d, 0xa5,
	0x20, 0x84, 0xc4, 0x29, 0x7e, 0x63, 0xe7, 0xbd, 0xb7, 0x33, 0xf3, 0x60, 0x5a, 0x66, 0xf2, 0x8e,
	0xea, 0x75, 0x25, 0x85, 0x16, 0x68, 0x64, 0x7f, 0xf0, 0x7b, 0x38, 0xff, 0x28, 0x34, 0xfb, 0x5a,
	0xbf, 0xdd, 0x69, 0x26, 0x38, 0xa1, 0xdf, 0xee, 0xa9, 0xd2, 0xe8, 0x29, 0x0c, 0xee, 0x59, 0x9e,
	0xf6, 0x2f, 0x7b, 0xab, 0x21, 0x31, 0x47, 0x57, 0xe1, 0xe9, 0x20, 0x54, 0xb8, 0xa9, 0x64, 0x3b,
	0x9d, 0x0e, 0x2f, 0x7b, 0xab, 0x09, 0x31, 0x47, 0xbc, 0x82, 0x79, 0x9b, 0x4c, 0x55, 0x82, 0x2b,
	0x6a, 0x5e, 0x96, 0x6a, 0x6f, 0xd9, 0x26, 0xc4, 0x1c, 0xf1, 0x35, 0xcc, 0xb6, 0x59, 0x7d, 0x53,
	0x08, 0xfd, 0x5b, 0x45, 0xc5, 0x72, 0xab, 0x78, 0x4a, 0xcc, 0x11, 0x2d, 0x20, 0x29, 0x05, 0xd7,
	0x07, 0x65, 0x45, 0x47, 0xc4, 0x23, 0xfc, 0x02, 0xce, 0x1a, 0x36, 0x2f, 0x99, 0xc2, 0xb8, 0xac,
	0x55, 0x21, 0xb4, 0xb2, 0x04, 0x53, 0x12, 0x20, 0xde, 0xc0, 0xf9, 0x35, 0x53, 0xfa, 0xb3, 0x92,
	0x37, 0x87, 0x4c, 0xd2, 0xc7, 0xf5, 0xe7, 0x30, 0x52, 0x3a, 0x93, 0xda, 0x12, 0x4c, 0x88, 0x03,
	0xe6, 0x1d, 0xe5, 0x79, 0xf8, 0x6a, 0xca, 0x73, 0xbc, 0x86, 0x79, 0x9b, 0xd0, 0x5b, 0x58, 0x40,
	0xa2, 0x4c, 0x21, 0x38, 0xf0, 0x28, 0x18, 0xd8, 0xc8, 0x7d, 0xd7, 0x80, 0x88, 0x06, 0xc4, 0xdf,
	0x1b, 0x88, 0x84, 0x7f, 0x30, 0x40, 0xe1, 0x74, 0x9b, 0xd5, 0x1b, 0xb9, 0x0f, 0xd2, 0x33, 0xe8,
	0x8b, 0xca, 0x2b, 0xf7, 0x45, 0x65, 0x9a, 0xb7, 0x3b, 0xd0, 0xdd, 0x1d, 0x95, 0x7e, 0xde, 0x01,
	0x06, 0x93, 0xc3, 0x68, 0x32, 0x85, 0x71, 0x95, 0xd5, 0x05, 0x53, 0x3a, 0x1d, 0xb9, 0x46, 0x7b,
	0x88, 0x73, 0x3b, 0x63, 0x2b, 0xe3, 0x0d, 0xfd, 0x8b, 0xce, 0x02, 0x92, 0x5b, 0x56, 0x14, 0x5c,
	0x58, 0x99, 0x09, 0xf1, 0x08, 0x7f, 0xef, 0xc1, 0x6c, 0x2b, 0xe9, 0x3b, 0x56, 0x14, 0x8f, 0x8f,
	0x32, 0x2e, 0x8e, 0xdb, 0x26, 0x8f, 0x6c, 0x87, 0xed, 0x8e, 0x0c, 0x6d, 0xd9, 0x01, 0x53, 0xad,
	0x0e, 0x82, 0x53, 0xaf, 0xe4, 0x00, 0x7a, 0x06, 0x4f, 0x2a, 0x49, 0xbf, 0x68, 0x56, 0xd2, 0x34,
	0xb1, 0x17, 0xe3, 0x4a, 0xd2, 0x4f, 0xac, 0xa4, 0xf8, 0x47, 0x0f, 0xce, 0x1a, 0x0f, 0x71, 0xe7,
	0xff, 0xab, 0x89, 0x97, 0x3f, 0x07, 0x90, 0x7c, 0xb0, 0x09, 0x47, 0x57, 0x30, 0x7d, 0x98, 0x43,
	0xb4, 0x74, 0x99, 0x5f, 0x1f, 0x49, 0xfa, 0xf2, 0xf9, 0xd1, 0x3b, 0xf7, 0x11, 0xf8, 0x04, 0xbd,
	0x81, 0xb1, 0x8f, 0x16, 0xba, 0xf0, 0x2f, 0xdb, 0xc1, 0x5d, 0x2e, 0xba, 0xe5, 0xe6, 0xbf, 0x57,
	0x30, 0x7d, 0x18, 0x8c, 0xc6, 0xc6, 0x91, 0xf8, 0x35, 0x36, 0x8e, 0x25, 0x29, 0x52, 0x85, 0x15,
	0x6f, 0x51, 0x75, 0x82, 0xd4, 0xa2, 0xea, 0x66, 0x02, 0x9f, 0xa0, 0xd7, 0x90, 0xb8, 0xb5, 0x44,
	0xf3, 0xe8, 0x3c, 0x86, 0x61, 0x79, 0xd1, 0xa9, 0xb6, 0x5a, 0xe1, 0x86, 0x1c, 0x5b, 0xd1, 0x5a,
	0xbc, 0xd8, 0x8a, 0xf6, 0x2e, 0xe0, 0x93, 0xdb, 0xc4, 0x5e, 0xbc, 0xfa, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xe5, 0x29, 0x3e, 0x69, 0x84, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketClient interface {
	NotifyAction(ctx context.Context, in *NotifyActionRequest, opts ...grpc.CallOption) (*NotifyActionResponse, error)
	PaySlot(ctx context.Context, in *PaySlotRequest, opts ...grpc.CallOption) (*PaySlotResponse, error)
	ListUsrShare(ctx context.Context, in *ListUsrShareRequest, opts ...grpc.CallOption) (*ListUsrShareResponse, error)
	ListOrgShare(ctx context.Context, in *ListOrgShareRequest, opts ...grpc.CallOption) (*ListOrgShareResponse, error)
	PayOrg(ctx context.Context, in *PayOrgRequest, opts ...grpc.CallOption) (*PayOrgResponse, error)
	PreBill(ctx context.Context, in *PreBillRequest, opts ...grpc.CallOption) (*PreBillResponse, error)
}

type marketClient struct {
	cc *grpc.ClientConn
}

func NewMarketClient(cc *grpc.ClientConn) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) NotifyAction(ctx context.Context, in *NotifyActionRequest, opts ...grpc.CallOption) (*NotifyActionResponse, error) {
	out := new(NotifyActionResponse)
	err := c.cc.Invoke(ctx, "/proto.Market/NotifyAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) PaySlot(ctx context.Context, in *PaySlotRequest, opts ...grpc.CallOption) (*PaySlotResponse, error) {
	out := new(PaySlotResponse)
	err := c.cc.Invoke(ctx, "/proto.Market/PaySlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) ListUsrShare(ctx context.Context, in *ListUsrShareRequest, opts ...grpc.CallOption) (*ListUsrShareResponse, error) {
	out := new(ListUsrShareResponse)
	err := c.cc.Invoke(ctx, "/proto.Market/ListUsrShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) ListOrgShare(ctx context.Context, in *ListOrgShareRequest, opts ...grpc.CallOption) (*ListOrgShareResponse, error) {
	out := new(ListOrgShareResponse)
	err := c.cc.Invoke(ctx, "/proto.Market/ListOrgShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) PayOrg(ctx context.Context, in *PayOrgRequest, opts ...grpc.CallOption) (*PayOrgResponse, error) {
	out := new(PayOrgResponse)
	err := c.cc.Invoke(ctx, "/proto.Market/PayOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) PreBill(ctx context.Context, in *PreBillRequest, opts ...grpc.CallOption) (*PreBillResponse, error) {
	out := new(PreBillResponse)
	err := c.cc.Invoke(ctx, "/proto.Market/PreBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
type MarketServer interface {
	NotifyAction(context.Context, *NotifyActionRequest) (*NotifyActionResponse, error)
	PaySlot(context.Context, *PaySlotRequest) (*PaySlotResponse, error)
	ListUsrShare(context.Context, *ListUsrShareRequest) (*ListUsrShareResponse, error)
	ListOrgShare(context.Context, *ListOrgShareRequest) (*ListOrgShareResponse, error)
	PayOrg(context.Context, *PayOrgRequest) (*PayOrgResponse, error)
	PreBill(context.Context, *PreBillRequest) (*PreBillResponse, error)
}

// UnimplementedMarketServer can be embedded to have forward compatible implementations.
type UnimplementedMarketServer struct {
}

func (*UnimplementedMarketServer) NotifyAction(ctx context.Context, req *NotifyActionRequest) (*NotifyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyAction not implemented")
}
func (*UnimplementedMarketServer) PaySlot(ctx context.Context, req *PaySlotRequest) (*PaySlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaySlot not implemented")
}
func (*UnimplementedMarketServer) ListUsrShare(ctx context.Context, req *ListUsrShareRequest) (*ListUsrShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsrShare not implemented")
}
func (*UnimplementedMarketServer) ListOrgShare(ctx context.Context, req *ListOrgShareRequest) (*ListOrgShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrgShare not implemented")
}
func (*UnimplementedMarketServer) PayOrg(ctx context.Context, req *PayOrgRequest) (*PayOrgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOrg not implemented")
}
func (*UnimplementedMarketServer) PreBill(ctx context.Context, req *PreBillRequest) (*PreBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreBill not implemented")
}

func RegisterMarketServer(s *grpc.Server, srv MarketServer) {
	s.RegisterService(&_Market_serviceDesc, srv)
}

func _Market_NotifyAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).NotifyAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Market/NotifyAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).NotifyAction(ctx, req.(*NotifyActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_PaySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).PaySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Market/PaySlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).PaySlot(ctx, req.(*PaySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_ListUsrShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsrShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).ListUsrShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Market/ListUsrShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).ListUsrShare(ctx, req.(*ListUsrShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_ListOrgShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).ListOrgShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Market/ListOrgShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).ListOrgShare(ctx, req.(*ListOrgShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_PayOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).PayOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Market/PayOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).PayOrg(ctx, req.(*PayOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_PreBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).PreBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Market/PreBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).PreBill(ctx, req.(*PreBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Market_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyAction",
			Handler:    _Market_NotifyAction_Handler,
		},
		{
			MethodName: "PaySlot",
			Handler:    _Market_PaySlot_Handler,
		},
		{
			MethodName: "ListUsrShare",
			Handler:    _Market_ListUsrShare_Handler,
		},
		{
			MethodName: "ListOrgShare",
			Handler:    _Market_ListOrgShare_Handler,
		},
		{
			MethodName: "PayOrg",
			Handler:    _Market_PayOrg_Handler,
		},
		{
			MethodName: "PreBill",
			Handler:    _Market_PreBill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}
