// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sns.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//////////for group////////////
type CreateGroupRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Permission           int32    `protobuf:"varint,5,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{0}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type CreateGroupResponse struct {
	Jsgroup              []byte   `protobuf:"bytes,4,opt,name=jsgroup,proto3" json:"jsgroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{1}
}

func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(m, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetJsgroup() []byte {
	if m != nil {
		return m.Jsgroup
	}
	return nil
}

type GetGroupsRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupsRequest) Reset()         { *m = GetGroupsRequest{} }
func (m *GetGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupsRequest) ProtoMessage()    {}
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{2}
}

func (m *GetGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsRequest.Unmarshal(m, b)
}
func (m *GetGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsRequest.Merge(m, src)
}
func (m *GetGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupsRequest.Size(m)
}
func (m *GetGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsRequest proto.InternalMessageInfo

func (m *GetGroupsRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetGroupResponse struct {
	Jsgroups             []byte   `protobuf:"bytes,4,opt,name=jsgroups,proto3" json:"jsgroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{3}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetJsgroups() []byte {
	if m != nil {
		return m.Jsgroups
	}
	return nil
}

type ApplyGroupRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyGroupRequest) Reset()         { *m = ApplyGroupRequest{} }
func (m *ApplyGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyGroupRequest) ProtoMessage()    {}
func (*ApplyGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{4}
}

func (m *ApplyGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyGroupRequest.Unmarshal(m, b)
}
func (m *ApplyGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyGroupRequest.Marshal(b, m, deterministic)
}
func (m *ApplyGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyGroupRequest.Merge(m, src)
}
func (m *ApplyGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyGroupRequest.Size(m)
}
func (m *ApplyGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyGroupRequest proto.InternalMessageInfo

func (m *ApplyGroupRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ApplyGroupRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type ApplyGroupResponse struct {
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Applyed              int32    `protobuf:"varint,5,opt,name=applyed,proto3" json:"applyed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyGroupResponse) Reset()         { *m = ApplyGroupResponse{} }
func (m *ApplyGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyGroupResponse) ProtoMessage()    {}
func (*ApplyGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{5}
}

func (m *ApplyGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyGroupResponse.Unmarshal(m, b)
}
func (m *ApplyGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyGroupResponse.Marshal(b, m, deterministic)
}
func (m *ApplyGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyGroupResponse.Merge(m, src)
}
func (m *ApplyGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyGroupResponse.Size(m)
}
func (m *ApplyGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyGroupResponse proto.InternalMessageInfo

func (m *ApplyGroupResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *ApplyGroupResponse) GetApplyed() int32 {
	if m != nil {
		return m.Applyed
	}
	return 0
}

type QuitGroupRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupRequest) Reset()         { *m = QuitGroupRequest{} }
func (m *QuitGroupRequest) String() string { return proto.CompactTextString(m) }
func (*QuitGroupRequest) ProtoMessage()    {}
func (*QuitGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{6}
}

func (m *QuitGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupRequest.Unmarshal(m, b)
}
func (m *QuitGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupRequest.Marshal(b, m, deterministic)
}
func (m *QuitGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupRequest.Merge(m, src)
}
func (m *QuitGroupRequest) XXX_Size() int {
	return xxx_messageInfo_QuitGroupRequest.Size(m)
}
func (m *QuitGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupRequest proto.InternalMessageInfo

func (m *QuitGroupRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *QuitGroupRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type QuitGroupResponse struct {
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Quit                 int32    `protobuf:"varint,5,opt,name=quit,proto3" json:"quit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupResponse) Reset()         { *m = QuitGroupResponse{} }
func (m *QuitGroupResponse) String() string { return proto.CompactTextString(m) }
func (*QuitGroupResponse) ProtoMessage()    {}
func (*QuitGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{7}
}

func (m *QuitGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupResponse.Unmarshal(m, b)
}
func (m *QuitGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupResponse.Marshal(b, m, deterministic)
}
func (m *QuitGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupResponse.Merge(m, src)
}
func (m *QuitGroupResponse) XXX_Size() int {
	return xxx_messageInfo_QuitGroupResponse.Size(m)
}
func (m *QuitGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupResponse proto.InternalMessageInfo

func (m *QuitGroupResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *QuitGroupResponse) GetQuit() int32 {
	if m != nil {
		return m.Quit
	}
	return 0
}

///////////group manage//////
type SetGroupRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Permission           int32    `protobuf:"varint,6,opt,name=permission,proto3" json:"permission,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Image                string   `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupRequest) Reset()         { *m = SetGroupRequest{} }
func (m *SetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*SetGroupRequest) ProtoMessage()    {}
func (*SetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{8}
}

func (m *SetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupRequest.Unmarshal(m, b)
}
func (m *SetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupRequest.Marshal(b, m, deterministic)
}
func (m *SetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupRequest.Merge(m, src)
}
func (m *SetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_SetGroupRequest.Size(m)
}
func (m *SetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupRequest proto.InternalMessageInfo

func (m *SetGroupRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SetGroupRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SetGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetGroupRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *SetGroupRequest) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *SetGroupRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SetGroupRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type SetGroupResponse struct {
	Gid                  uint64   `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Jsgroup              []byte   `protobuf:"bytes,4,opt,name=jsgroup,proto3" json:"jsgroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupResponse) Reset()         { *m = SetGroupResponse{} }
func (m *SetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*SetGroupResponse) ProtoMessage()    {}
func (*SetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{9}
}

func (m *SetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupResponse.Unmarshal(m, b)
}
func (m *SetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupResponse.Marshal(b, m, deterministic)
}
func (m *SetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupResponse.Merge(m, src)
}
func (m *SetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_SetGroupResponse.Size(m)
}
func (m *SetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupResponse proto.InternalMessageInfo

func (m *SetGroupResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SetGroupResponse) GetJsgroup() []byte {
	if m != nil {
		return m.Jsgroup
	}
	return nil
}

type SetManagerRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Uin                  uint64   `protobuf:"varint,5,opt,name=uin,proto3" json:"uin,omitempty"`
	Operate              int32    `protobuf:"varint,6,opt,name=operate,proto3" json:"operate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetManagerRequest) Reset()         { *m = SetManagerRequest{} }
func (m *SetManagerRequest) String() string { return proto.CompactTextString(m) }
func (*SetManagerRequest) ProtoMessage()    {}
func (*SetManagerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{10}
}

func (m *SetManagerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetManagerRequest.Unmarshal(m, b)
}
func (m *SetManagerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetManagerRequest.Marshal(b, m, deterministic)
}
func (m *SetManagerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetManagerRequest.Merge(m, src)
}
func (m *SetManagerRequest) XXX_Size() int {
	return xxx_messageInfo_SetManagerRequest.Size(m)
}
func (m *SetManagerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetManagerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetManagerRequest proto.InternalMessageInfo

func (m *SetManagerRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SetManagerRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SetManagerRequest) GetUin() uint64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *SetManagerRequest) GetOperate() int32 {
	if m != nil {
		return m.Operate
	}
	return 0
}

type SetManagerResponse struct {
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Managers             []uint64 `protobuf:"varint,5,rep,packed,name=managers,proto3" json:"managers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetManagerResponse) Reset()         { *m = SetManagerResponse{} }
func (m *SetManagerResponse) String() string { return proto.CompactTextString(m) }
func (*SetManagerResponse) ProtoMessage()    {}
func (*SetManagerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{11}
}

func (m *SetManagerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetManagerResponse.Unmarshal(m, b)
}
func (m *SetManagerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetManagerResponse.Marshal(b, m, deterministic)
}
func (m *SetManagerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetManagerResponse.Merge(m, src)
}
func (m *SetManagerResponse) XXX_Size() int {
	return xxx_messageInfo_SetManagerResponse.Size(m)
}
func (m *SetManagerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetManagerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetManagerResponse proto.InternalMessageInfo

func (m *SetManagerResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SetManagerResponse) GetManagers() []uint64 {
	if m != nil {
		return m.Managers
	}
	return nil
}

type ListApplyRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplyRequest) Reset()         { *m = ListApplyRequest{} }
func (m *ListApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplyRequest) ProtoMessage()    {}
func (*ListApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{12}
}

func (m *ListApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplyRequest.Unmarshal(m, b)
}
func (m *ListApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplyRequest.Marshal(b, m, deterministic)
}
func (m *ListApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplyRequest.Merge(m, src)
}
func (m *ListApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplyRequest.Size(m)
}
func (m *ListApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplyRequest proto.InternalMessageInfo

func (m *ListApplyRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListApplyRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type ListApplyResponse struct {
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Applicant            []uint64 `protobuf:"varint,5,rep,packed,name=Applicant,proto3" json:"Applicant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplyResponse) Reset()         { *m = ListApplyResponse{} }
func (m *ListApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplyResponse) ProtoMessage()    {}
func (*ListApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{13}
}

func (m *ListApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplyResponse.Unmarshal(m, b)
}
func (m *ListApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplyResponse.Marshal(b, m, deterministic)
}
func (m *ListApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplyResponse.Merge(m, src)
}
func (m *ListApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplyResponse.Size(m)
}
func (m *ListApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplyResponse proto.InternalMessageInfo

func (m *ListApplyResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *ListApplyResponse) GetApplicant() []uint64 {
	if m != nil {
		return m.Applicant
	}
	return nil
}

type AcceptMemberRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Uin                  uint64   `protobuf:"varint,5,opt,name=uin,proto3" json:"uin,omitempty"`
	Accept               int32    `protobuf:"varint,6,opt,name=accept,proto3" json:"accept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptMemberRequest) Reset()         { *m = AcceptMemberRequest{} }
func (m *AcceptMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptMemberRequest) ProtoMessage()    {}
func (*AcceptMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{14}
}

func (m *AcceptMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptMemberRequest.Unmarshal(m, b)
}
func (m *AcceptMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptMemberRequest.Marshal(b, m, deterministic)
}
func (m *AcceptMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptMemberRequest.Merge(m, src)
}
func (m *AcceptMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptMemberRequest.Size(m)
}
func (m *AcceptMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptMemberRequest proto.InternalMessageInfo

func (m *AcceptMemberRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AcceptMemberRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *AcceptMemberRequest) GetUin() uint64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *AcceptMemberRequest) GetAccept() int32 {
	if m != nil {
		return m.Accept
	}
	return 0
}

type AcceptMemberResponse struct {
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Members              []uint64 `protobuf:"varint,5,rep,packed,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptMemberResponse) Reset()         { *m = AcceptMemberResponse{} }
func (m *AcceptMemberResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptMemberResponse) ProtoMessage()    {}
func (*AcceptMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{15}
}

func (m *AcceptMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptMemberResponse.Unmarshal(m, b)
}
func (m *AcceptMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptMemberResponse.Marshal(b, m, deterministic)
}
func (m *AcceptMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptMemberResponse.Merge(m, src)
}
func (m *AcceptMemberResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptMemberResponse.Size(m)
}
func (m *AcceptMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptMemberResponse proto.InternalMessageInfo

func (m *AcceptMemberResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *AcceptMemberResponse) GetMembers() []uint64 {
	if m != nil {
		return m.Members
	}
	return nil
}

////////// for topic manage////////////
type CreateTopicRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicRequest) Reset()         { *m = CreateTopicRequest{} }
func (m *CreateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicRequest) ProtoMessage()    {}
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{16}
}

func (m *CreateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicRequest.Unmarshal(m, b)
}
func (m *CreateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicRequest.Merge(m, src)
}
func (m *CreateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicRequest.Size(m)
}
func (m *CreateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicRequest proto.InternalMessageInfo

func (m *CreateTopicRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateTopicRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *CreateTopicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTopicRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type CreateTopicResponse struct {
	Jstopics             []byte   `protobuf:"bytes,5,opt,name=jstopics,proto3" json:"jstopics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicResponse) Reset()         { *m = CreateTopicResponse{} }
func (m *CreateTopicResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTopicResponse) ProtoMessage()    {}
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{17}
}

func (m *CreateTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicResponse.Unmarshal(m, b)
}
func (m *CreateTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicResponse.Marshal(b, m, deterministic)
}
func (m *CreateTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicResponse.Merge(m, src)
}
func (m *CreateTopicResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTopicResponse.Size(m)
}
func (m *CreateTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicResponse proto.InternalMessageInfo

func (m *CreateTopicResponse) GetJstopics() []byte {
	if m != nil {
		return m.Jstopics
	}
	return nil
}

type SetTopicRequest struct {
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Symbol               string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Image                string   `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTopicRequest) Reset()         { *m = SetTopicRequest{} }
func (m *SetTopicRequest) String() string { return proto.CompactTextString(m) }
func (*SetTopicRequest) ProtoMessage()    {}
func (*SetTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{18}
}

func (m *SetTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTopicRequest.Unmarshal(m, b)
}
func (m *SetTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTopicRequest.Marshal(b, m, deterministic)
}
func (m *SetTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTopicRequest.Merge(m, src)
}
func (m *SetTopicRequest) XXX_Size() int {
	return xxx_messageInfo_SetTopicRequest.Size(m)
}
func (m *SetTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTopicRequest proto.InternalMessageInfo

func (m *SetTopicRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SetTopicRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SetTopicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetTopicRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SetTopicRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *SetTopicRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SetTopicRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type SetTopicResponse struct {
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Jstopics             []byte   `protobuf:"bytes,5,opt,name=jstopics,proto3" json:"jstopics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTopicResponse) Reset()         { *m = SetTopicResponse{} }
func (m *SetTopicResponse) String() string { return proto.CompactTextString(m) }
func (*SetTopicResponse) ProtoMessage()    {}
func (*SetTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{19}
}

func (m *SetTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTopicResponse.Unmarshal(m, b)
}
func (m *SetTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTopicResponse.Marshal(b, m, deterministic)
}
func (m *SetTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTopicResponse.Merge(m, src)
}
func (m *SetTopicResponse) XXX_Size() int {
	return xxx_messageInfo_SetTopicResponse.Size(m)
}
func (m *SetTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTopicResponse proto.InternalMessageInfo

func (m *SetTopicResponse) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SetTopicResponse) GetJstopics() []byte {
	if m != nil {
		return m.Jstopics
	}
	return nil
}

////////for post///////////////
type PubPostRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Pid                  uint64   `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Text                 string   `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Attacher             []string `protobuf:"bytes,7,rep,name=attacher,proto3" json:"attacher,omitempty"`
	Nick                 string   `protobuf:"bytes,8,opt,name=nick,proto3" json:"nick,omitempty"`
	Avatar               string   `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubPostRequest) Reset()         { *m = PubPostRequest{} }
func (m *PubPostRequest) String() string { return proto.CompactTextString(m) }
func (*PubPostRequest) ProtoMessage()    {}
func (*PubPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{20}
}

func (m *PubPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubPostRequest.Unmarshal(m, b)
}
func (m *PubPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubPostRequest.Marshal(b, m, deterministic)
}
func (m *PubPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubPostRequest.Merge(m, src)
}
func (m *PubPostRequest) XXX_Size() int {
	return xxx_messageInfo_PubPostRequest.Size(m)
}
func (m *PubPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PubPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PubPostRequest proto.InternalMessageInfo

func (m *PubPostRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PubPostRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *PubPostRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PubPostRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *PubPostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PubPostRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PubPostRequest) GetAttacher() []string {
	if m != nil {
		return m.Attacher
	}
	return nil
}

func (m *PubPostRequest) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *PubPostRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type PubPostResponse struct {
	Jspost               []byte   `protobuf:"bytes,3,opt,name=jspost,proto3" json:"jspost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubPostResponse) Reset()         { *m = PubPostResponse{} }
func (m *PubPostResponse) String() string { return proto.CompactTextString(m) }
func (*PubPostResponse) ProtoMessage()    {}
func (*PubPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{21}
}

func (m *PubPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubPostResponse.Unmarshal(m, b)
}
func (m *PubPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubPostResponse.Marshal(b, m, deterministic)
}
func (m *PubPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubPostResponse.Merge(m, src)
}
func (m *PubPostResponse) XXX_Size() int {
	return xxx_messageInfo_PubPostResponse.Size(m)
}
func (m *PubPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PubPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PubPostResponse proto.InternalMessageInfo

func (m *PubPostResponse) GetJspost() []byte {
	if m != nil {
		return m.Jspost
	}
	return nil
}

////for group post /////
type ListPostRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint64   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Dir                  int32    `protobuf:"varint,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Lastpid              uint64   `protobuf:"varint,6,opt,name=lastpid,proto3" json:"lastpid,omitempty"`
	Filter               string   `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostRequest) Reset()         { *m = ListPostRequest{} }
func (m *ListPostRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostRequest) ProtoMessage()    {}
func (*ListPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{22}
}

func (m *ListPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostRequest.Unmarshal(m, b)
}
func (m *ListPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostRequest.Marshal(b, m, deterministic)
}
func (m *ListPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostRequest.Merge(m, src)
}
func (m *ListPostRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostRequest.Size(m)
}
func (m *ListPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostRequest proto.InternalMessageInfo

func (m *ListPostRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListPostRequest) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *ListPostRequest) GetDir() int32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *ListPostRequest) GetLastpid() uint64 {
	if m != nil {
		return m.Lastpid
	}
	return 0
}

func (m *ListPostRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ListPostResponse struct {
	Jspost               []byte   `protobuf:"bytes,6,opt,name=jspost,proto3" json:"jspost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostResponse) Reset()         { *m = ListPostResponse{} }
func (m *ListPostResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostResponse) ProtoMessage()    {}
func (*ListPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{23}
}

func (m *ListPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostResponse.Unmarshal(m, b)
}
func (m *ListPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostResponse.Marshal(b, m, deterministic)
}
func (m *ListPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostResponse.Merge(m, src)
}
func (m *ListPostResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostResponse.Size(m)
}
func (m *ListPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostResponse proto.InternalMessageInfo

func (m *ListPostResponse) GetJspost() []byte {
	if m != nil {
		return m.Jspost
	}
	return nil
}

////default ：dir = 0
type GroupsPostRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gids                 []uint64 `protobuf:"varint,4,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupsPostRequest) Reset()         { *m = GroupsPostRequest{} }
func (m *GroupsPostRequest) String() string { return proto.CompactTextString(m) }
func (*GroupsPostRequest) ProtoMessage()    {}
func (*GroupsPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{24}
}

func (m *GroupsPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupsPostRequest.Unmarshal(m, b)
}
func (m *GroupsPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupsPostRequest.Marshal(b, m, deterministic)
}
func (m *GroupsPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupsPostRequest.Merge(m, src)
}
func (m *GroupsPostRequest) XXX_Size() int {
	return xxx_messageInfo_GroupsPostRequest.Size(m)
}
func (m *GroupsPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupsPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupsPostRequest proto.InternalMessageInfo

func (m *GroupsPostRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GroupsPostRequest) GetGids() []uint64 {
	if m != nil {
		return m.Gids
	}
	return nil
}

type GroupsPostResponse struct {
	Jsposts              []byte   `protobuf:"bytes,6,opt,name=jsposts,proto3" json:"jsposts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupsPostResponse) Reset()         { *m = GroupsPostResponse{} }
func (m *GroupsPostResponse) String() string { return proto.CompactTextString(m) }
func (*GroupsPostResponse) ProtoMessage()    {}
func (*GroupsPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{25}
}

func (m *GroupsPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupsPostResponse.Unmarshal(m, b)
}
func (m *GroupsPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupsPostResponse.Marshal(b, m, deterministic)
}
func (m *GroupsPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupsPostResponse.Merge(m, src)
}
func (m *GroupsPostResponse) XXX_Size() int {
	return xxx_messageInfo_GroupsPostResponse.Size(m)
}
func (m *GroupsPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupsPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupsPostResponse proto.InternalMessageInfo

func (m *GroupsPostResponse) GetJsposts() []byte {
	if m != nil {
		return m.Jsposts
	}
	return nil
}

type LikePostRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostRequest) Reset()         { *m = LikePostRequest{} }
func (m *LikePostRequest) String() string { return proto.CompactTextString(m) }
func (*LikePostRequest) ProtoMessage()    {}
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{26}
}

func (m *LikePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostRequest.Unmarshal(m, b)
}
func (m *LikePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostRequest.Marshal(b, m, deterministic)
}
func (m *LikePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostRequest.Merge(m, src)
}
func (m *LikePostRequest) XXX_Size() int {
	return xxx_messageInfo_LikePostRequest.Size(m)
}
func (m *LikePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostRequest proto.InternalMessageInfo

func (m *LikePostRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LikePostRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type LikePostResponse struct {
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Count                int32    `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostResponse) Reset()         { *m = LikePostResponse{} }
func (m *LikePostResponse) String() string { return proto.CompactTextString(m) }
func (*LikePostResponse) ProtoMessage()    {}
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{27}
}

func (m *LikePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostResponse.Unmarshal(m, b)
}
func (m *LikePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostResponse.Marshal(b, m, deterministic)
}
func (m *LikePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostResponse.Merge(m, src)
}
func (m *LikePostResponse) XXX_Size() int {
	return xxx_messageInfo_LikePostResponse.Size(m)
}
func (m *LikePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostResponse proto.InternalMessageInfo

func (m *LikePostResponse) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *LikePostResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeletePostRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{28}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DeletePostRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type DeletePostResponse struct {
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Deleted              int32    `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{29}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

func (m *DeletePostResponse) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *DeletePostResponse) GetDeleted() int32 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

/////////////////reply topic/////////
type ReplyPostRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Rid                  uint64   `protobuf:"varint,7,opt,name=rid,proto3" json:"rid,omitempty"`
	Text                 string   `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	Mynick               string   `protobuf:"bytes,9,opt,name=mynick,proto3" json:"mynick,omitempty"`
	Tonick               string   `protobuf:"bytes,10,opt,name=tonick,proto3" json:"tonick,omitempty"`
	Touin                uint64   `protobuf:"varint,11,opt,name=touin,proto3" json:"touin,omitempty"`
	Attacher             []string `protobuf:"bytes,12,rep,name=attacher,proto3" json:"attacher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyPostRequest) Reset()         { *m = ReplyPostRequest{} }
func (m *ReplyPostRequest) String() string { return proto.CompactTextString(m) }
func (*ReplyPostRequest) ProtoMessage()    {}
func (*ReplyPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{30}
}

func (m *ReplyPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPostRequest.Unmarshal(m, b)
}
func (m *ReplyPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPostRequest.Marshal(b, m, deterministic)
}
func (m *ReplyPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPostRequest.Merge(m, src)
}
func (m *ReplyPostRequest) XXX_Size() int {
	return xxx_messageInfo_ReplyPostRequest.Size(m)
}
func (m *ReplyPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPostRequest proto.InternalMessageInfo

func (m *ReplyPostRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ReplyPostRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ReplyPostRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *ReplyPostRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ReplyPostRequest) GetMynick() string {
	if m != nil {
		return m.Mynick
	}
	return ""
}

func (m *ReplyPostRequest) GetTonick() string {
	if m != nil {
		return m.Tonick
	}
	return ""
}

func (m *ReplyPostRequest) GetTouin() uint64 {
	if m != nil {
		return m.Touin
	}
	return 0
}

func (m *ReplyPostRequest) GetAttacher() []string {
	if m != nil {
		return m.Attacher
	}
	return nil
}

type ReplyPostResponse struct {
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Jsreply              []byte   `protobuf:"bytes,7,opt,name=jsreply,proto3" json:"jsreply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyPostResponse) Reset()         { *m = ReplyPostResponse{} }
func (m *ReplyPostResponse) String() string { return proto.CompactTextString(m) }
func (*ReplyPostResponse) ProtoMessage()    {}
func (*ReplyPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{31}
}

func (m *ReplyPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPostResponse.Unmarshal(m, b)
}
func (m *ReplyPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPostResponse.Marshal(b, m, deterministic)
}
func (m *ReplyPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPostResponse.Merge(m, src)
}
func (m *ReplyPostResponse) XXX_Size() int {
	return xxx_messageInfo_ReplyPostResponse.Size(m)
}
func (m *ReplyPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPostResponse proto.InternalMessageInfo

func (m *ReplyPostResponse) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ReplyPostResponse) GetJsreply() []byte {
	if m != nil {
		return m.Jsreply
	}
	return nil
}

type DeleteReplyRequest struct {
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Rid                  uint64   `protobuf:"varint,7,opt,name=rid,proto3" json:"rid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReplyRequest) Reset()         { *m = DeleteReplyRequest{} }
func (m *DeleteReplyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReplyRequest) ProtoMessage()    {}
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{32}
}

func (m *DeleteReplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReplyRequest.Unmarshal(m, b)
}
func (m *DeleteReplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReplyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReplyRequest.Merge(m, src)
}
func (m *DeleteReplyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReplyRequest.Size(m)
}
func (m *DeleteReplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReplyRequest proto.InternalMessageInfo

func (m *DeleteReplyRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DeleteReplyRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *DeleteReplyRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

type DeleteReplyResponse struct {
	Pid                  uint64   `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Rid                  uint64   `protobuf:"varint,7,opt,name=rid,proto3" json:"rid,omitempty"`
	Deleted              int32    `protobuf:"varint,8,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReplyResponse) Reset()         { *m = DeleteReplyResponse{} }
func (m *DeleteReplyResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReplyResponse) ProtoMessage()    {}
func (*DeleteReplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dbc22f4a220f680, []int{33}
}

func (m *DeleteReplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReplyResponse.Unmarshal(m, b)
}
func (m *DeleteReplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReplyResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReplyResponse.Merge(m, src)
}
func (m *DeleteReplyResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReplyResponse.Size(m)
}
func (m *DeleteReplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReplyResponse proto.InternalMessageInfo

func (m *DeleteReplyResponse) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *DeleteReplyResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeleteReplyResponse) GetDeleted() int32 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateGroupRequest)(nil), "proto.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "proto.CreateGroupResponse")
	proto.RegisterType((*GetGroupsRequest)(nil), "proto.GetGroupsRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "proto.GetGroupResponse")
	proto.RegisterType((*ApplyGroupRequest)(nil), "proto.ApplyGroupRequest")
	proto.RegisterType((*ApplyGroupResponse)(nil), "proto.ApplyGroupResponse")
	proto.RegisterType((*QuitGroupRequest)(nil), "proto.QuitGroupRequest")
	proto.RegisterType((*QuitGroupResponse)(nil), "proto.QuitGroupResponse")
	proto.RegisterType((*SetGroupRequest)(nil), "proto.SetGroupRequest")
	proto.RegisterType((*SetGroupResponse)(nil), "proto.SetGroupResponse")
	proto.RegisterType((*SetManagerRequest)(nil), "proto.SetManagerRequest")
	proto.RegisterType((*SetManagerResponse)(nil), "proto.SetManagerResponse")
	proto.RegisterType((*ListApplyRequest)(nil), "proto.ListApplyRequest")
	proto.RegisterType((*ListApplyResponse)(nil), "proto.ListApplyResponse")
	proto.RegisterType((*AcceptMemberRequest)(nil), "proto.AcceptMemberRequest")
	proto.RegisterType((*AcceptMemberResponse)(nil), "proto.AcceptMemberResponse")
	proto.RegisterType((*CreateTopicRequest)(nil), "proto.CreateTopicRequest")
	proto.RegisterType((*CreateTopicResponse)(nil), "proto.CreateTopicResponse")
	proto.RegisterType((*SetTopicRequest)(nil), "proto.SetTopicRequest")
	proto.RegisterType((*SetTopicResponse)(nil), "proto.SetTopicResponse")
	proto.RegisterType((*PubPostRequest)(nil), "proto.PubPostRequest")
	proto.RegisterType((*PubPostResponse)(nil), "proto.PubPostResponse")
	proto.RegisterType((*ListPostRequest)(nil), "proto.ListPostRequest")
	proto.RegisterType((*ListPostResponse)(nil), "proto.ListPostResponse")
	proto.RegisterType((*GroupsPostRequest)(nil), "proto.GroupsPostRequest")
	proto.RegisterType((*GroupsPostResponse)(nil), "proto.GroupsPostResponse")
	proto.RegisterType((*LikePostRequest)(nil), "proto.LikePostRequest")
	proto.RegisterType((*LikePostResponse)(nil), "proto.LikePostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "proto.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "proto.DeletePostResponse")
	proto.RegisterType((*ReplyPostRequest)(nil), "proto.ReplyPostRequest")
	proto.RegisterType((*ReplyPostResponse)(nil), "proto.ReplyPostResponse")
	proto.RegisterType((*DeleteReplyRequest)(nil), "proto.DeleteReplyRequest")
	proto.RegisterType((*DeleteReplyResponse)(nil), "proto.DeleteReplyResponse")
}

func init() { proto.RegisterFile("sns.proto", fileDescriptor_8dbc22f4a220f680) }

var fileDescriptor_8dbc22f4a220f680 = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x9e, 0x6c, 0x7e, 0x26, 0xa9, 0x1d, 0x31, 0x49, 0xcf, 0x90, 0xf1, 0x1a, 0x84, 0xa2, 0x16,
	0x87, 0xc0, 0x61, 0x10, 0x20, 0x40, 0xbb, 0x12, 0xec, 0xec, 0x0e, 0x62, 0x05, 0x62, 0xa5, 0xc5,
	0xe1, 0xc4, 0x09, 0x8f, 0xd3, 0x04, 0xcf, 0x26, 0xb1, 0xd7, 0xdd, 0x41, 0xe4, 0x79, 0x38, 0xf2,
	0x0e, 0x3c, 0x02, 0x2f, 0xc4, 0x05, 0x75, 0xf5, 0x8f, 0xdb, 0x6e, 0x7b, 0x46, 0xd1, 0x9e, 0xdc,
	0xd5, 0xae, 0xae, 0xaa, 0xaf, 0xfa, 0xeb, 0xaa, 0x82, 0x11, 0xdf, 0xf2, 0xcb, 0xbc, 0xc8, 0x44,
	0x46, 0xfa, 0xf8, 0xa1, 0xbf, 0x00, 0xb9, 0x2e, 0x58, 0x2c, 0xd8, 0x8b, 0x22, 0xdb, 0xe5, 0x11,
	0x7b, 0xb3, 0x63, 0x5c, 0x90, 0x31, 0x74, 0x77, 0xe9, 0x32, 0xe8, 0xce, 0x3a, 0xf3, 0x5e, 0x24,
	0x97, 0x84, 0x40, 0x6f, 0x1b, 0x6f, 0x58, 0xd0, 0x9b, 0x75, 0xe6, 0xa3, 0x08, 0xd7, 0xe4, 0x03,
	0x80, 0x9c, 0x15, 0x9b, 0x94, 0xf3, 0x34, 0xdb, 0x06, 0xfd, 0x59, 0x67, 0xde, 0x8f, 0x9c, 0x1d,
	0xfa, 0x09, 0x9c, 0x55, 0x6c, 0xf3, 0x3c, 0xdb, 0x72, 0x46, 0x02, 0x38, 0xbe, 0xe5, 0x2b, 0xb9,
	0x85, 0xd6, 0x4e, 0x22, 0x23, 0xd2, 0x0f, 0x61, 0xfc, 0x82, 0x09, 0xd4, 0xe6, 0xad, 0xa1, 0xd0,
	0xcb, 0x52, 0xcb, 0xda, 0x0c, 0x61, 0xa8, 0x8d, 0x70, 0x6d, 0xd4, 0xca, 0xf4, 0x2b, 0x98, 0x3c,
	0xcb, 0xf3, 0xf5, 0xfe, 0x1e, 0x84, 0x63, 0xe8, 0xae, 0xd2, 0x25, 0x9e, 0xee, 0x45, 0x72, 0x49,
	0xaf, 0x80, 0xb8, 0x07, 0xb5, 0x2b, 0x4f, 0x4f, 0x02, 0x8a, 0xa5, 0x1e, 0x5b, 0xea, 0x24, 0x18,
	0x91, 0x7e, 0x09, 0xe3, 0x9f, 0x76, 0xa9, 0x38, 0xd8, 0xf3, 0x63, 0x98, 0x38, 0xe7, 0x5a, 0x1d,
	0x13, 0xe8, 0xbd, 0xd9, 0xa5, 0x42, 0x7b, 0xc5, 0x35, 0xfd, 0xbb, 0x03, 0xa7, 0x0b, 0xd6, 0xe8,
	0xf2, 0x81, 0xe7, 0xb2, 0x5b, 0xb1, 0xe5, 0x5d, 0x30, 0x81, 0xde, 0x92, 0xf1, 0x04, 0xed, 0x8f,
	0x22, 0x5c, 0xd7, 0x2e, 0x7d, 0x50, 0xbf, 0x74, 0x32, 0x85, 0x01, 0x17, 0xb1, 0xd8, 0xf1, 0xe0,
	0x18, 0xff, 0x69, 0x89, 0x9c, 0x43, 0x3f, 0xdd, 0xc4, 0x2b, 0x16, 0x0c, 0xd1, 0x98, 0x12, 0xe8,
	0x37, 0x30, 0x5e, 0xb0, 0x66, 0x9c, 0xdd, 0x4a, 0x82, 0x5b, 0x18, 0x93, 0xc0, 0x64, 0xc1, 0xc4,
	0xcb, 0x78, 0x1b, 0xaf, 0x58, 0x71, 0x40, 0x86, 0x95, 0x8e, 0x22, 0x2d, 0xea, 0x6c, 0xa5, 0x93,
	0x2c, 0x67, 0x45, 0x2c, 0x98, 0x46, 0x65, 0x44, 0xfa, 0x1c, 0x88, 0xeb, 0xa4, 0xf5, 0x3a, 0x42,
	0x18, 0x6e, 0x94, 0x12, 0x0f, 0xfa, 0xb3, 0xee, 0xbc, 0x17, 0x59, 0x59, 0x32, 0xe1, 0xc7, 0x94,
	0x0b, 0xe4, 0xd3, 0x21, 0x4c, 0xb8, 0x86, 0x89, 0x73, 0xae, 0xd5, 0xf5, 0xfb, 0x30, 0x92, 0x2a,
	0x69, 0x12, 0x6f, 0x85, 0xf6, 0x5d, 0x6e, 0xd0, 0x04, 0xce, 0x9e, 0x25, 0x09, 0xcb, 0xc5, 0x4b,
	0xb6, 0xb9, 0x79, 0xdb, 0x3c, 0x4d, 0x61, 0x10, 0xa3, 0x31, 0x9d, 0x26, 0x2d, 0xd1, 0xe7, 0x70,
	0x5e, 0x75, 0x72, 0xd7, 0x7b, 0xd9, 0xa0, 0x8e, 0x49, 0x93, 0x11, 0xe9, 0xaf, 0xa6, 0x1a, 0xfd,
	0x9c, 0xe5, 0x69, 0x72, 0x48, 0x9c, 0x86, 0xbe, 0xfd, 0x06, 0xfa, 0x0e, 0x4a, 0xfa, 0xd2, 0x4f,
	0x4d, 0x4d, 0xd2, 0x1e, 0xdc, 0xfa, 0x21, 0xe4, 0x16, 0x47, 0x13, 0x58, 0x3f, 0x94, 0x4c, 0xff,
	0x52, 0x2f, 0xaa, 0x29, 0xa4, 0x83, 0x5f, 0x94, 0x7c, 0x1d, 0xfb, 0xcd, 0x4d, 0xb6, 0xd6, 0x81,
	0x6a, 0xa9, 0x29, 0xd4, 0x03, 0x5f, 0xd2, 0x15, 0xbe, 0xa4, 0x2a, 0xaa, 0x46, 0x8a, 0xb6, 0xe2,
	0xfc, 0xb7, 0x03, 0xef, 0xbc, 0xda, 0xdd, 0xbc, 0xca, 0xb8, 0xa8, 0xc1, 0xec, 0x78, 0x30, 0x1f,
	0x94, 0x26, 0xcf, 0xa1, 0x8f, 0x06, 0x10, 0xfa, 0x28, 0x52, 0x82, 0xd4, 0xcb, 0x4b, 0xd7, 0xb9,
	0xd6, 0x4b, 0xc5, 0xda, 0x5c, 0x91, 0x12, 0x24, 0x70, 0xc1, 0xfe, 0x14, 0x06, 0xb8, 0x5c, 0xcb,
	0x20, 0x63, 0x21, 0xe2, 0xe4, 0x77, 0x56, 0x04, 0xc7, 0xb3, 0xee, 0x7c, 0x14, 0x59, 0x19, 0x93,
	0x9a, 0x26, 0xaf, 0x35, 0x76, 0x5c, 0x23, 0x23, 0xff, 0x88, 0x45, 0x5c, 0x04, 0x23, 0x95, 0x54,
	0x25, 0xd1, 0x8f, 0xe0, 0xd4, 0xe2, 0xd1, 0x19, 0x99, 0xc2, 0xe0, 0x96, 0xe7, 0x19, 0x17, 0x18,
	0xed, 0x49, 0xa4, 0x25, 0xba, 0x87, 0x53, 0xf9, 0xcc, 0x1a, 0xb0, 0xdf, 0xf7, 0x3a, 0x96, 0x69,
	0xa1, 0xeb, 0xaf, 0x5c, 0x4a, 0x6e, 0xaf, 0x63, 0x2e, 0x24, 0xf6, 0x01, 0xea, 0x19, 0x51, 0xba,
	0xfe, 0x2d, 0x5d, 0x0b, 0xc4, 0x84, 0x51, 0x2a, 0x89, 0x7e, 0xac, 0x2a, 0x43, 0x4b, 0x98, 0x83,
	0x4a, 0x98, 0x8f, 0x61, 0xa2, 0xba, 0xe3, 0xdd, 0x81, 0x12, 0xe8, 0xad, 0xd2, 0xa5, 0xec, 0x84,
	0xf2, 0x75, 0xe1, 0x9a, 0x5e, 0x02, 0x71, 0x8f, 0xba, 0xbd, 0x58, 0x9a, 0xe6, 0xda, 0x93, 0x11,
	0xe9, 0x17, 0x32, 0x23, 0xaf, 0xd9, 0xbd, 0x19, 0x29, 0x91, 0xca, 0x25, 0x7d, 0x22, 0xd1, 0x98,
	0x63, 0x25, 0x0d, 0xab, 0x5a, 0x92, 0x0b, 0x49, 0xb6, 0xdb, 0x0a, 0xcd, 0x6c, 0x25, 0xc8, 0x46,
	0xfd, 0x2d, 0x5b, 0x33, 0x71, 0xb0, 0xd3, 0x2b, 0x20, 0xee, 0xc1, 0x56, 0xb7, 0x01, 0x1c, 0x2f,
	0x51, 0x6f, 0xa9, 0x1d, 0x1b, 0x91, 0xfe, 0xd3, 0x81, 0x71, 0xc4, 0xf2, 0xf5, 0xfe, 0x40, 0xd7,
	0x72, 0xa7, 0x48, 0x95, 0xb9, 0x5e, 0x24, 0x97, 0x96, 0xd1, 0x43, 0x87, 0xd1, 0x53, 0x18, 0x6c,
	0xf6, 0xc8, 0x5b, 0xcd, 0x50, 0x25, 0xc9, 0x7d, 0x91, 0xe1, 0x3e, 0xa8, 0x7d, 0x25, 0xa9, 0x37,
	0x25, 0xeb, 0xee, 0x43, 0xb4, 0xab, 0x84, 0xca, 0xbb, 0x38, 0xa9, 0xbe, 0x0b, 0xfa, 0x14, 0x26,
	0x4e, 0xfc, 0x77, 0x65, 0xe0, 0x96, 0x17, 0x52, 0x11, 0x43, 0xc6, 0xfb, 0x46, 0x91, 0xfe, 0x60,
	0x72, 0x88, 0x66, 0xde, 0x2a, 0x05, 0x74, 0x01, 0x67, 0x15, 0x5b, 0xad, 0xe1, 0xf8, 0xd9, 0x73,
	0xae, 0x68, 0x58, 0xb9, 0xa2, 0xcf, 0xfe, 0x1b, 0x42, 0x77, 0xb1, 0xe5, 0xe4, 0x3b, 0x78, 0xe8,
	0x4c, 0x95, 0xe4, 0x91, 0x9a, 0x67, 0x2f, 0xfd, 0x29, 0x36, 0x0c, 0x9b, 0x7e, 0xa9, 0x58, 0xe8,
	0x11, 0x79, 0x0a, 0x23, 0x3b, 0x6c, 0x92, 0x0b, 0xad, 0x5a, 0x1f, 0x3f, 0xc3, 0xfa, 0x0f, 0xc7,
	0xc0, 0x35, 0x40, 0x39, 0x1e, 0x92, 0x40, 0x2b, 0x7a, 0xa3, 0x66, 0xf8, 0xa8, 0xe1, 0x8f, 0x35,
	0x72, 0x05, 0x23, 0x3b, 0xe9, 0xd9, 0x28, 0xea, 0x33, 0x63, 0x18, 0xf8, 0x3f, 0xac, 0x85, 0xaf,
	0x61, 0x68, 0x46, 0x28, 0x32, 0xd5, 0x7a, 0xb5, 0x01, 0xd0, 0xa2, 0x58, 0x34, 0xa2, 0x28, 0x87,
	0x1b, 0x8b, 0xc2, 0x1b, 0xaa, 0x2c, 0x0a, 0x7f, 0x12, 0x52, 0x28, 0xec, 0x94, 0x62, 0x51, 0xd4,
	0xe7, 0x1d, 0x8b, 0xc2, 0x1b, 0x68, 0xe8, 0x11, 0xf9, 0x1e, 0x4e, 0xdc, 0xe9, 0x81, 0x98, 0xbb,
	0x6b, 0x98, 0x5b, 0xc2, 0xf7, 0x1a, 0xff, 0x59, 0x53, 0x96, 0x20, 0xd8, 0x0c, 0x6b, 0x04, 0x71,
	0xbb, 0x78, 0x8d, 0x20, 0x95, 0xde, 0x69, 0x13, 0xab, 0x8c, 0x38, 0x89, 0xad, 0x58, 0xb8, 0xf0,
	0xf6, 0xed, 0xf1, 0x27, 0x70, 0xac, 0xbb, 0x0f, 0x79, 0x57, 0x6b, 0x55, 0xbb, 0x6b, 0x38, 0xad,
	0x6f, 0xbb, 0xae, 0x4d, 0x4f, 0xb0, 0xae, 0x6b, 0xfd, 0x29, 0xbc, 0xf0, 0xf6, 0xdd, 0x3b, 0x2d,
	0x6b, 0xbd, 0xbd, 0x53, 0xaf, 0x73, 0xd8, 0x3b, 0xf5, 0x1b, 0x83, 0x89, 0x41, 0x55, 0x72, 0x27,
	0x86, 0x4a, 0x47, 0x70, 0x62, 0xa8, 0x96, 0x7c, 0x15, 0x43, 0x59, 0x93, 0x6d, 0x0c, 0x5e, 0x7d,
	0xb7, 0x31, 0xf8, 0x05, 0x5c, 0xf1, 0xca, 0x56, 0x35, 0xcb, 0xab, 0x7a, 0x9d, 0xb6, 0xbc, 0xf2,
	0x0a, 0xa0, 0x22, 0x83, 0x53, 0x8a, 0x48, 0xd5, 0x9b, 0x5b, 0xea, 0x2c, 0x19, 0x1a, 0x2a, 0x17,
	0x3d, 0xba, 0x19, 0xe0, 0xcf, 0xcf, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x99, 0x82, 0xbd, 0x99,
	0x42, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnsClient is the client API for Sns service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnsClient interface {
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	ApplyGroup(ctx context.Context, in *ApplyGroupRequest, opts ...grpc.CallOption) (*ApplyGroupResponse, error)
	QuitGroup(ctx context.Context, in *QuitGroupRequest, opts ...grpc.CallOption) (*QuitGroupResponse, error)
	//////for manage//////////
	SetGroup(ctx context.Context, in *SetGroupRequest, opts ...grpc.CallOption) (*SetGroupResponse, error)
	SetManager(ctx context.Context, in *SetManagerRequest, opts ...grpc.CallOption) (*SetManagerResponse, error)
	ListApply(ctx context.Context, in *ListApplyRequest, opts ...grpc.CallOption) (*ListApplyResponse, error)
	AcceptMember(ctx context.Context, in *AcceptMemberRequest, opts ...grpc.CallOption) (*AcceptMemberResponse, error)
	///////for topic///////
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	SetTopic(ctx context.Context, in *SetTopicRequest, opts ...grpc.CallOption) (*SetTopicResponse, error)
	////for post/////////
	PubPost(ctx context.Context, in *PubPostRequest, opts ...grpc.CallOption) (*PubPostResponse, error)
	ListPost(ctx context.Context, in *ListPostRequest, opts ...grpc.CallOption) (*ListPostResponse, error)
	GroupsPost(ctx context.Context, in *GroupsPostRequest, opts ...grpc.CallOption) (*GroupsPostResponse, error)
	LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	//////for reply///////
	ReplyPost(ctx context.Context, in *ReplyPostRequest, opts ...grpc.CallOption) (*ReplyPostResponse, error)
	DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error)
}

type snsClient struct {
	cc *grpc.ClientConn
}

func NewSnsClient(cc *grpc.ClientConn) SnsClient {
	return &snsClient{cc}
}

func (c *snsClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/GetGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) ApplyGroup(ctx context.Context, in *ApplyGroupRequest, opts ...grpc.CallOption) (*ApplyGroupResponse, error) {
	out := new(ApplyGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/ApplyGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) QuitGroup(ctx context.Context, in *QuitGroupRequest, opts ...grpc.CallOption) (*QuitGroupResponse, error) {
	out := new(QuitGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/QuitGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) SetGroup(ctx context.Context, in *SetGroupRequest, opts ...grpc.CallOption) (*SetGroupResponse, error) {
	out := new(SetGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/SetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) SetManager(ctx context.Context, in *SetManagerRequest, opts ...grpc.CallOption) (*SetManagerResponse, error) {
	out := new(SetManagerResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/SetManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) ListApply(ctx context.Context, in *ListApplyRequest, opts ...grpc.CallOption) (*ListApplyResponse, error) {
	out := new(ListApplyResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/ListApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) AcceptMember(ctx context.Context, in *AcceptMemberRequest, opts ...grpc.CallOption) (*AcceptMemberResponse, error) {
	out := new(AcceptMemberResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/AcceptMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) SetTopic(ctx context.Context, in *SetTopicRequest, opts ...grpc.CallOption) (*SetTopicResponse, error) {
	out := new(SetTopicResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/SetTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) PubPost(ctx context.Context, in *PubPostRequest, opts ...grpc.CallOption) (*PubPostResponse, error) {
	out := new(PubPostResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/PubPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) ListPost(ctx context.Context, in *ListPostRequest, opts ...grpc.CallOption) (*ListPostResponse, error) {
	out := new(ListPostResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/ListPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) GroupsPost(ctx context.Context, in *GroupsPostRequest, opts ...grpc.CallOption) (*GroupsPostResponse, error) {
	out := new(GroupsPostResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/GroupsPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error) {
	out := new(LikePostResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/LikePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) ReplyPost(ctx context.Context, in *ReplyPostRequest, opts ...grpc.CallOption) (*ReplyPostResponse, error) {
	out := new(ReplyPostResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/ReplyPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snsClient) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*DeleteReplyResponse, error) {
	out := new(DeleteReplyResponse)
	err := c.cc.Invoke(ctx, "/proto.Sns/DeleteReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnsServer is the server API for Sns service.
type SnsServer interface {
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupResponse, error)
	ApplyGroup(context.Context, *ApplyGroupRequest) (*ApplyGroupResponse, error)
	QuitGroup(context.Context, *QuitGroupRequest) (*QuitGroupResponse, error)
	//////for manage//////////
	SetGroup(context.Context, *SetGroupRequest) (*SetGroupResponse, error)
	SetManager(context.Context, *SetManagerRequest) (*SetManagerResponse, error)
	ListApply(context.Context, *ListApplyRequest) (*ListApplyResponse, error)
	AcceptMember(context.Context, *AcceptMemberRequest) (*AcceptMemberResponse, error)
	///////for topic///////
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	SetTopic(context.Context, *SetTopicRequest) (*SetTopicResponse, error)
	////for post/////////
	PubPost(context.Context, *PubPostRequest) (*PubPostResponse, error)
	ListPost(context.Context, *ListPostRequest) (*ListPostResponse, error)
	GroupsPost(context.Context, *GroupsPostRequest) (*GroupsPostResponse, error)
	LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	//////for reply///////
	ReplyPost(context.Context, *ReplyPostRequest) (*ReplyPostResponse, error)
	DeleteReply(context.Context, *DeleteReplyRequest) (*DeleteReplyResponse, error)
}

// UnimplementedSnsServer can be embedded to have forward compatible implementations.
type UnimplementedSnsServer struct {
}

func (*UnimplementedSnsServer) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedSnsServer) GetGroups(ctx context.Context, req *GetGroupsRequest) (*GetGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroups not implemented")
}
func (*UnimplementedSnsServer) ApplyGroup(ctx context.Context, req *ApplyGroupRequest) (*ApplyGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyGroup not implemented")
}
func (*UnimplementedSnsServer) QuitGroup(ctx context.Context, req *QuitGroupRequest) (*QuitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitGroup not implemented")
}
func (*UnimplementedSnsServer) SetGroup(ctx context.Context, req *SetGroupRequest) (*SetGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGroup not implemented")
}
func (*UnimplementedSnsServer) SetManager(ctx context.Context, req *SetManagerRequest) (*SetManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetManager not implemented")
}
func (*UnimplementedSnsServer) ListApply(ctx context.Context, req *ListApplyRequest) (*ListApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApply not implemented")
}
func (*UnimplementedSnsServer) AcceptMember(ctx context.Context, req *AcceptMemberRequest) (*AcceptMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptMember not implemented")
}
func (*UnimplementedSnsServer) CreateTopic(ctx context.Context, req *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (*UnimplementedSnsServer) SetTopic(ctx context.Context, req *SetTopicRequest) (*SetTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTopic not implemented")
}
func (*UnimplementedSnsServer) PubPost(ctx context.Context, req *PubPostRequest) (*PubPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PubPost not implemented")
}
func (*UnimplementedSnsServer) ListPost(ctx context.Context, req *ListPostRequest) (*ListPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPost not implemented")
}
func (*UnimplementedSnsServer) GroupsPost(ctx context.Context, req *GroupsPostRequest) (*GroupsPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupsPost not implemented")
}
func (*UnimplementedSnsServer) LikePost(ctx context.Context, req *LikePostRequest) (*LikePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikePost not implemented")
}
func (*UnimplementedSnsServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedSnsServer) ReplyPost(ctx context.Context, req *ReplyPostRequest) (*ReplyPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyPost not implemented")
}
func (*UnimplementedSnsServer) DeleteReply(ctx context.Context, req *DeleteReplyRequest) (*DeleteReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReply not implemented")
}

func RegisterSnsServer(s *grpc.Server, srv SnsServer) {
	s.RegisterService(&_Sns_serviceDesc, srv)
}

func _Sns_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/GetGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_ApplyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).ApplyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/ApplyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).ApplyGroup(ctx, req.(*ApplyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_QuitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).QuitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/QuitGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).QuitGroup(ctx, req.(*QuitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_SetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).SetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/SetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).SetGroup(ctx, req.(*SetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_SetManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).SetManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/SetManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).SetManager(ctx, req.(*SetManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_ListApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).ListApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/ListApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).ListApply(ctx, req.(*ListApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_AcceptMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).AcceptMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/AcceptMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).AcceptMember(ctx, req.(*AcceptMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_SetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).SetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/SetTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).SetTopic(ctx, req.(*SetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_PubPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).PubPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/PubPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).PubPost(ctx, req.(*PubPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_ListPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).ListPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/ListPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).ListPost(ctx, req.(*ListPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_GroupsPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).GroupsPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/GroupsPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).GroupsPost(ctx, req.(*GroupsPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/LikePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).LikePost(ctx, req.(*LikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_ReplyPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).ReplyPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/ReplyPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).ReplyPost(ctx, req.(*ReplyPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sns_DeleteReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnsServer).DeleteReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sns/DeleteReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnsServer).DeleteReply(ctx, req.(*DeleteReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sns_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sns",
	HandlerType: (*SnsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _Sns_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroups",
			Handler:    _Sns_GetGroups_Handler,
		},
		{
			MethodName: "ApplyGroup",
			Handler:    _Sns_ApplyGroup_Handler,
		},
		{
			MethodName: "QuitGroup",
			Handler:    _Sns_QuitGroup_Handler,
		},
		{
			MethodName: "SetGroup",
			Handler:    _Sns_SetGroup_Handler,
		},
		{
			MethodName: "SetManager",
			Handler:    _Sns_SetManager_Handler,
		},
		{
			MethodName: "ListApply",
			Handler:    _Sns_ListApply_Handler,
		},
		{
			MethodName: "AcceptMember",
			Handler:    _Sns_AcceptMember_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _Sns_CreateTopic_Handler,
		},
		{
			MethodName: "SetTopic",
			Handler:    _Sns_SetTopic_Handler,
		},
		{
			MethodName: "PubPost",
			Handler:    _Sns_PubPost_Handler,
		},
		{
			MethodName: "ListPost",
			Handler:    _Sns_ListPost_Handler,
		},
		{
			MethodName: "GroupsPost",
			Handler:    _Sns_GroupsPost_Handler,
		},
		{
			MethodName: "LikePost",
			Handler:    _Sns_LikePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Sns_DeletePost_Handler,
		},
		{
			MethodName: "ReplyPost",
			Handler:    _Sns_ReplyPost_Handler,
		},
		{
			MethodName: "DeleteReply",
			Handler:    _Sns_DeleteReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sns.proto",
}
